### ISSUE TITLE
"Resources" links are broken

### ISSUE THREAD

**Issue by MikkelSchubert** [rust-bio/rust-htslib#10]
The links in the README.md file are either outdated or broken:

- "Homepage: https://github.com/christopher-schroeder/rust-htslib" - Outdated, but redirects to the correct page.
- "API documentation: http://christopher-schroeder.github.io/rust-htslib" - Broken.
- "Continuous integration tests: https://travis-ci.org/christopher-schroeder/rust-htslib" - Broken.

Cheers

**Comment by johanneskoester** [comment]
Thanks! I have updated them. Unlike with Rust-Bio, documentation is still sparse at the moment. We need to extend it as soon as possible.
