### ISSUE TITLE
design review of unpack_cigar

### ISSUE THREAD

**Issue by pmarks** [rust-bio/rust-htslib#100]
Hi @johanneskoester,
 
I've been fixing up some code to work with current master.  I wanted to discuss the new unpack_cigar design. I think I understand the motivation: to cache the 'decoded' Cigar, to avoid unpacking it cigar multiple times. 

My concerns around this change are:
 - a breaking change to a frequently used API - need to change a lot of code
 - cigar() now returns None if you forget to call unpack_cigar, which is confusing and now requires reasoning about whether / when to call unpack_cigar().
 - A function that wants to read the cigar now either needs a `&mut Record`, or needs the caller to ensure that unpack_cigar has been called --  can lead to borrow-checking complications, and makes the function signature of methods somewhat less informative (because they might need a &mut Record, even though they don't edit the Record)

I would like to see if there's some way to preserve the existing 'no-mutability, redo unpacking' API, and expose the higher-performance scheme you've added with unpack_cigar. Here's a simple proposal that might give us the best of both world:

- Switch cigar() to the back old signature.  If there's a cached unpacked cigar, clone that and return it. Otherwise, unpack the cigar and return an owned copy.
- Keep unpack_cigar as is.
- Rename the current cigar() to cigar_cached() that provides the 'high performance' accessor.

Thoughts? (I'd be happy to make a PR to implement my suggestion)

**Comment by veldsla** [comment]
I agree with @pmarks concerns.
I'm not even sure why you would want to cache the CigarString in the record at all when you return an owned version. Why not leave the caching to the library user? There are no functions in `Record` that operate on the unpacked `CigarString` so why keep it around?

**Comment by johanneskoester** [comment]
It can be quite a performance impact if you read the cigar string multiple times for one record. With the previous solution, caching is indeed up to the user. When doing this in practice, I found it making the code unnecessarily verbose, if you use cigar in a lot of places. With the current solution, you get a much more convenient API, at the only expense that you have to call unpack_cigar once. But you can do that at the beginning, directly after reading the record, where you have mutable access anyway. Hence, there should be no clashes with the borrow checker. Yes, it is a breaking change, but nothing that cannot be resolved with a simple search and replace, giving you faster code for free.

However, if you still think the previous functionality is also needed, I am fine with accepting a PR that restores it in the way you describe @pmarks.

**Comment by johanneskoester** [comment]
@pmarks sorry for being so quiet in the last days. I promise to come back to your other stuff ASAP. Likely not before Thursday though, I have a very crowded schedule these days... All this is really appreciated!

**Comment by johanneskoester** [comment]
@veldsla this is indeed a valid use case. Ok, let's switch back to `cigar()` as it was before, and have `cigar_cached()` with the current functionality, plus rename `unpack_cigar()` into `cache_cigar()`.

**Comment by johanneskoester** [comment]
I don't know how fast I will be able to do that, so any help would be greatly appreciated!

**Comment by pmarks** [comment]
@johanneskoester I'll make a PR today.
