### ISSUE TITLE
I can't build it!

### ISSUE THREAD

**Issue by jraikisto** [rust-bio/rust-htslib#103]
cargo build

Compiling rust-htslib v0.20.0
error: failed to run custom build command for `rust-htslib v0.20.0`
process didn't exit successfully: `/Users/MyUser/MyProject/target/debug/build/rust-htslib-cceb9dd97ea2b9e6/build-script-build` (exit code: 101)
--- stdout
echo '/* Default config.h generated by Makefile */' > config.h
echo '#define HAVE_LIBBZ2 1' >> config.h
echo '#define HAVE_LIBLZMA 1' >> config.h
echo '#define HAVE_FSEEKO 1' >> config.h
echo '#define HAVE_DRAND48 1' >> config.h
gcc -g -Wall -O2 -fPIC -I.  -c -o kfunc.o kfunc.c
gcc -g -Wall -O2 -fPIC -I.  -c -o knetfile.o knetfile.c
gcc -g -Wall -O2 -fPIC -I.  -c -o kstring.o kstring.c
gcc -g -Wall -O2 -fPIC -I.  -c -o bcf_sr_sort.o bcf_sr_sort.c
gcc -g -Wall -O2 -fPIC -I.  -c -o bgzf.o bgzf.c
gcc -g -Wall -O2 -fPIC -I.  -c -o errmod.o errmod.c
gcc -g -Wall -O2 -fPIC -I.  -c -o faidx.o faidx.c
gcc -g -Wall -O2 -fPIC -I.  -c -o hfile.o hfile.c
gcc -g -Wall -O2 -fPIC -I.  -c -o hfile_net.o hfile_net.c
echo '#define HTS_VERSION "1.6"' > version.h
gcc -g -Wall -O2 -fPIC -I.  -c -o hts.o hts.c
gcc -g -Wall -O2 -fPIC -I.  -c -o hts_os.o hts_os.c
gcc -g -Wall -O2 -fPIC -I.  -c -o md5.o md5.c
gcc -g -Wall -O2 -fPIC -I.  -c -o multipart.o multipart.c
gcc -g -Wall -O2 -fPIC -I.  -c -o probaln.o probaln.c
gcc -g -Wall -O2 -fPIC -I.  -c -o realn.o realn.c
gcc -g -Wall -O2 -fPIC -I.  -c -o regidx.o regidx.c
gcc -g -Wall -O2 -fPIC -I.  -c -o sam.o sam.c
gcc -g -Wall -O2 -fPIC -I.  -c -o synced_bcf_reader.o synced_bcf_reader.c
gcc -g -Wall -O2 -fPIC -I.  -c -o vcf_sweep.o vcf_sweep.c
gcc -g -Wall -O2 -fPIC -I.  -c -o tbx.o tbx.c
gcc -g -Wall -O2 -fPIC -I.  -c -o textutils.o textutils.c
gcc -g -Wall -O2 -fPIC -I.  -c -o thread_pool.o thread_pool.c
gcc -g -Wall -O2 -fPIC -I.  -c -o vcf.o vcf.c
gcc -g -Wall -O2 -fPIC -I.  -c -o vcfutils.o vcfutils.c
gcc -g -Wall -O2 -fPIC -I.  -c -o cram/cram_codecs.o cram/cram_codecs.c
gcc -g -Wall -O2 -fPIC -I.  -c -o cram/cram_decode.o cram/cram_decode.c
gcc -g -Wall -O2 -fPIC -I.  -c -o cram/cram_encode.o cram/cram_encode.c
gcc -g -Wall -O2 -fPIC -I.  -c -o cram/cram_external.o cram/cram_external.c
gcc -g -Wall -O2 -fPIC -I.  -c -o cram/cram_index.o cram/cram_index.c
gcc -g -Wall -O2 -fPIC -I.  -c -o cram/cram_io.o cram/cram_io.c

--- stderr
cram/cram_io.c:60:10: fatal error: 'lzma.h' file not found
#include <lzma.h>
         ^
1 error generated.
make: *** [cram/cram_io.o] Error 1
thread 'main' panicked at 'failed to build htslib', /Users/MyUser/.cargo/registry/src/github.com-1ecc6299db9ec823/rust-htslib-0.20.0/build.rs:30:9
note: Run with `RUST_BACKTRACE=1` for a backtrace.

rustc --version
rustc 1.27.2 (58cc626de 2018-07-18)

OS version:
macOS 10.13.6

I'm new to rust so I hope this is something very trivial but I couldn't get my head around this one. (Not even after extensive googling)

**Comment by johanneskoester** [comment]
You have to make lzma.h available in your system. E.g., on Ubuntu Linux, this is simply `$ apt-get install -y liblzma-dev`. On macOS, you can use either homebrew or conda to install lzma. If you are interested in bioinformatics anyway, it is probably best to use conda and benefit from the rest of the ecosystem, e.g. https://bioconda.github.io.

**Comment by jraikisto** [comment]
Thanks!!
