### ISSUE TITLE
"extern crate htslib" doesn't work

### ISSUE THREAD

**Issue by sitag** [rust-bio/rust-htslib#11]
documentation out of date - even `extern crate htslib` doesn't work. need to use `rust_htslib.` bunch of other things needed to get a simple bam reader up and running: https://github.com/sitag/BamUtils/blob/master/src/main.rs

**Comment by johanneskoester** [comment]
Indeed, it seems like the API docs are no longer updated properly. I will have a look.

Thank you!

**Comment by johanneskoester** [comment]
Checked it, the API docs are up to date. But I had to update the README.

Thanks!
