### ISSUE TITLE
pileup contain pair reads and dup reads

### ISSUE THREAD

**Issue by TuBieJun** [rust-bio/rust-htslib#113]
Hi, I find the records of bam::pileup include read-pair and dup reads . This is  different with samtools mpileup and pysam. So could you please give some paramters to filter these reads ? By the way, could you please give a method  to  bam::pileup to select a specific mut pos?

**Comment by juliangehring** [comment]
It should be easy to implement your custom filtering on top of the `pileup` output. The rust-bio-tools have an [example](https://github.com/rust-bio/rust-bio-tools/blob/master/src/bam/depth.rs#L85-L93) for it:

```rust
let depth = pileup
    .alignments()
    .filter(|alignment| {
        let record = alignment.record();
        let flags = record.flags();
        (!flags) & include_flags == 0
        && flags & exclude_flags == 0
        && record.mapq() >= min_mapq
    })
    .count();
```

`pileup` also has options for [setting a specific query position](https://docs.rs/rust-htslib/0.24.0/rust_htslib/bam/pileup/struct.Pileup.html) directly.

**Comment by johanneskoester** [comment]
For the position, this can be combined with `fetch` from `IndexedReader`.
