### ISSUE TITLE
CRAM support

### ISSUE THREAD

**Issue by juliangehring** [rust-bio/rust-htslib#116]
Out of curiosity, are there plans to add a high-level interface for reading/writing CRAM files?

**Comment by johanneskoester** [comment]
High level in what sense? The current bam module of rust-htslib already supports reading and writing CRAM I think. Or am I missing something?

**Comment by juliangehring** [comment]
How would I provide the [reference genome file](http://www.htslib.org/doc/samtools.html#REFERENCE_SEQUENCES) with the current interface? I don't see where this would need to go with the current `bam::Reader::from_path(&"test/test.cram").unwrap();` - but maybe I'm missing something here.

**Comment by juliangehring** [comment]
Let's use a [small, public data set](https://github.com/Illumina/strelka/tree/v2.9.x/src/demo/data) to make it more concrete:
The BAM files are already there, we can build the matching CRAM files with e.g.
```sh
samtools view -C -T demo20.fa -o NA12891_demo20.cram NA12891_demo20.bam
```
With
```rust
use rust_htslib::bam;   // rust_htslib v0.22.0
let mut bam = bam::Reader::from_path(&path).unwrap();
```
reading the BAM file `NA12891_demo20.bam` works fine, but trying to read the CRAM file fails with:

> [W::bam_hdr_read] EOF marker is absent. The input is probably truncated
[E::bam_hdr_read] Invalid BAM binary header
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Invalid', libcore/result.rs:1009:5

**Comment by johanneskoester** [comment]
Thanks for letting me know. You are right then! I always assumed the bam reader is format-agnostic. So, yes, in that case, adding CRAM support is definitely an intended feature now. However, I must admit that my schedule is so tight that I would need help in order to get this done quickly. Hence I cannot promise a timeline. However, I am happy to accept any PRs.

**Comment by juliangehring** [comment]
Thanks, it would be neat to have cram support in the library as well. I'm happy to help where I can, but my knowledge of the htslib internals is very limited - not sure if I can be of big help here.

**Comment by juliangehring** [comment]
#123 brought in all the basic functionality for reading and writing CRAM files.
Thanks @jfarek!
