### ISSUE TITLE
How to get read length from bam::Record?

### ISSUE THREAD

**Issue by gusevfe** [rust-bio/rust-htslib#12]
Hi!

Why is seq_len() private? https://github.com/rust-bio/rust-htslib/blob/master/src/bam/record.rs#L221

There is a len() method in Seq, but it always returns an even number (because the sequence is packed). This function is not private, and it is very confusing. https://github.com/rust-bio/rust-htslib/blob/master/src/bam/record.rs#L383

There is an option to use qual().len() to get read length; however this would not work when qualities are not present (e.g. mapping of FASTA files).

I propose to:
* make seq_len() public to make it possible to get read length,
* make Seq::len() private to reduce confusion.

**Comment by johanneskoester** [comment]
I fixed it in pull request #13. Now the len function of the Seq object returns the proper length. It does not copy anything, so performance should be fine. Does it work for you?

**Comment by gusevfe** [comment]
Yep, seems to work fine.

On Sat, Oct 31, 2015 at 5:44 PM, Johannes Köster <notifications@github.com>
wrote:

> I fixed it in pull request #13
> <https://github.com/rust-bio/rust-htslib/pull/13>. Now the len function
> of the Seq object returns the proper length. It does not copy anything, so
> performance should be fine. Does it work for you?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rust-bio/rust-htslib/issues/12#issuecomment-152737920>
> .
>



-- 
Kind regards,
Fedor Gusev.
