### ISSUE TITLE
Pileups set_max_depth conversion overflow

### ISSUE THREAD

**Issue by landesfeind** [rust-bio/rust-htslib#120]
Hi,
the API for setting the maximum depth of a pileup expects a `u32` and converts to `i32` in an unsafe block. This can result to undesired behavior when providing a `depth > i32::max_value()`  because I think htslib falls back to the default 800.
```
pub fn set_max_depth(&mut self, depth: u32) {
        unsafe {
            htslib::bam_plp_set_maxcnt(self.itr, depth as i32);
        }
    }
```
I would be in favor of breaking the API and let `depth: i32`. Otherwise we could implement some checks here. Would Rust panic on an overflow when doing the conversion outside of the `unsafe` block?

If you tell me your preferred way of handling this, I implement a PR and some tests :-)

**Comment by johanneskoester** [comment]
Thanks for pointing this out! I think I am in favour of a check, because a negative depth makes no sense.

**Comment by landesfeind** [comment]
Implemented in https://github.com/rust-bio/rust-htslib/pull/122

Sorry it took so long, but was quite busy

**Comment by johanneskoester** [comment]
Thanks a lot!
