### ISSUE TITLE
Beyond wrapping htslib

### ISSUE THREAD

**Issue by TyberiusPrime** [rust-bio/rust-htslib#128]
Dear authors,

pysam greatly enhances htslib with functions that for example find all pairs of aligned positions between a read and the reference, or all aligned blocks, or the splice sites defined by a read.

I've implemented some of them for my own usage and was wondering
whether such a contribution would be welcome, or if you'd rather have them live in a separate module.

**Comment by johanneskoester** [comment]
That would be very welcome! Thank you!
