### ISSUE TITLE
Handle invalid files in the BAM reader

### ISSUE THREAD

**Issue by juliangehring** [rust-bio/rust-htslib#130]
The `bam::Reader` currently crashes when the input is not a BAM/CRAM/SAM file. For example, if one accidentally tries to read a VCF file:

```rust
Reader::from_path("test/test_various.vcf")
```

the entire program aborts fairly ungracefully. Is there a nice way of catching this, and e.g. returning a variant of a `ReaderPathError`? I guess one could manually check the first few bytes of the file before creating a Reader, but does htslib have some built-in capabilities for this that one could leverage?

**Comment by johanneskoester** [comment]
Thanks a lot for reporting! Not that I know of. But if you find something or implement a workaround, I would be happy to accept a PR!

**Comment by TyberiusPrime** [comment]
I guess one could check at least for the bgzip magic header?
The file *must* start with 1f 8b.

 Together with the BAM magic header (which get's compressed though, I believe), we should be able to discriminate BAM files.

**Comment by juliangehring** [comment]
I explored some options in htslib, and `htslib::hts_detect_format` might be a good option for checking that basic format requirements are met. It should also work with all relevant file formats. But I didn't had a lot of time to explore it further - I might find more time over the weekend.
`htslib::hts_check_EOF` might also be a possible solution, but it doesn't work in all circumstances.

**Comment by juliangehring** [comment]
The crash of `Reader::from_path` is caused by [`sam_hdr_read`](https://github.com/rust-bio/rust-htslib/blob/master/src/bam/mod.rs#L158) failing in an unsafe block (since there isn't a valid SAM header). It seems to me that pysam's checking for the header would likely fail as well.

**Comment by TyberiusPrime** [comment]
@juliangehring  you're right of course. I was trying with the current pysam (which does something different) but reading the source to an old version....

Either hts_detect_format or hts_format_description seem good candidates.

**Comment by TyberiusPrime** [comment]
I tried this:
```
unsafe {
            let mut fmt: htslib::htsFormat = std::mem::zeroed();
            htslib::hts_detect_format((*htsfile).fp.hfile, &mut fmt);
...
        }

but unfortunatly it segfaults in test_read_cram.

**Comment by juliangehring** [comment]
I'm not sure about the api here, but should `fmt` be one of `htsExactFormat_*` or `htsFormatCategory_sequence_data`?

**Comment by TyberiusPrime** [comment]
No, it takes a struct ```int hts_detect_format(hFILE *hfile, htsFormat *fmt)```.

The two enums are the fmt->category and fmt->format members of that struct.

And some of the bam-using tests do pass. 
Hm.

**Comment by juliangehring** [comment]
Okay, I see.

**Comment by TyberiusPrime** [comment]
Actually, hts_open already puts a format member on the htsfile struct. Narf ;).

PR immanent.
