### ISSUE TITLE
Header from BAM file is not parser

### ISSUE THREAD

**Issue by slazicoicr** [rust-bio/rust-htslib#134]
I downloaded a test BAM file at http://hgdownload.cse.ucsc.edu/goldenPath/hg19/encodeDCC/wgEncodeUwRepliSeq/wgEncodeUwRepliSeqK562G1AlnRep1.bam. Running `samtools view -H` to extract the header produces

```
@SQ	SN:chr1	LN:249250621
@SQ	SN:chr2	LN:243199373
@SQ	SN:chr3	LN:198022430
@SQ	SN:chr4	LN:191154276
@SQ	SN:chr5	LN:180915260
@SQ	SN:chr6	LN:171115067
@SQ	SN:chr7	LN:159138663
@SQ	SN:chr8	LN:146364022
@SQ	SN:chr9	LN:141213431
@SQ	SN:chr10	LN:135534747
@SQ	SN:chr11	LN:135006516
@SQ	SN:chr12	LN:133851895
@SQ	SN:chr13	LN:115169878
@SQ	SN:chr14	LN:107349540
@SQ	SN:chr15	LN:102531392
@SQ	SN:chr16	LN:90354753
@SQ	SN:chr17	LN:81195210
@SQ	SN:chr18	LN:78077248
@SQ	SN:chr19	LN:59128983
@SQ	SN:chr20	LN:63025520
@SQ	SN:chr21	LN:48129895
@SQ	SN:chr22	LN:51304566
@SQ	SN:chrM	LN:16571
@SQ	SN:chrX	LN:155270560
```

However, when I try to extract it with 
```
let bam = Reader::from_path(&"test.bam").unwrap();
let header = Header::from_template(bam.header());
println!("{:?}", header.to_hashmap());
```
an empty HashMap is returned. Further, if I try to save a new BAM file with the header `Writer::from_path(&"out.bam", &header).unwrap();` the resulting BAM file has no header information.

Am I missing something about parsing BAM headers?

**Comment by slazicoicr** [comment]
I figured out that it was the missing `@HD` line that was causing the issue. Adding it causes the code above to parse the header.

I think this is a bug. The specifications at https://samtools.github.io/hts-specs/SAMv1.pdf suggest that the `@HD` be present (Page 9), but it is not mandatory (Page 2). Both `samtools` and [pysam](https://pysam.readthedocs.io/en/latest/api.html) correctly parse the header above.

**Comment by juliangehring** [comment]
@slazicoicr I'm not sure if it is really the `@HD` line that is causing the issue: With your original bam file, I also get an empty header when parsing it with rust-htslib. But after converting the bam to sam and back to bam (no changes to the file), rust parses it with a full header. That doesn't really explain why samtools and pysam are doing fine on that file, but maybe there is something odd with the file itself?

**Comment by juliangehring** [comment]
@slazicoicr Where you able to find out why the header couldn't be read?

**Comment by slazicoicr** [comment]
I moved on to actual in house BAM files and they work fine. Strange issue, but it can be closed.

**Comment by brainstorm** [comment]
Closing in favour of https://github.com/rust-bio/rust-htslib/issues/156.
