### ISSUE TITLE
extract bases from nibble encoding

### ISSUE THREAD

**Issue by PoisonAlien** [rust-bio/rust-htslib#135]
Hello htslib-team,
How can I convert encoded bases to IUPAC bases from [Seq](https://docs.rs/rust-htslib/0.23.0/rust_htslib/bam/record/struct.Seq.html) method? I see C htslib has [bam_seqi](https://github.com/samtools/htslib/blob/f5a6a87c77e5179d7aad476c64973f3a6514584b/htslib/sam.h#L192) macro for converting. Is there a similar thing in rust lib? 

Here is my demo code:

```rust
extern crate rust_htslib;

use rust_htslib::bam;
use rust_htslib::prelude::*;
use rust_htslib::bam::Record;

use std::env;
use std::process;

fn main() {
    
    let args: Vec<String> = env::args().collect();

    if args.len() < 2 {
        println!("Usage: bamreader <foo.bam>");
        process::exit(0);
    }

    let bam_file = args[1].clone();

    let mut bamf = bam::Reader::from_path(&bam_file).unwrap();

    for r in bamf.records() {
        let record = r.unwrap();
        extract_sc(&record);
    }
}

fn extract_sc(rec: &Record) {
//How do I print IUPAC bases? Below prints encoded bases
    println!("{:?}", rec.seq().as_bytes());
}
```

I am new to rust and been playing around for learning purpose. Please accept my apologies if this has been already documented elsewhere.

**Comment by dlaehnemann** [comment]
Hi @PoisonAlien,

from a quick look at the [`Seq` methods documentation](https://docs.rs/rust-htslib/0.23.0/rust_htslib/bam/record/struct.Seq.html#methods) I would think that the `as_bytes()`you are using is the closest to what you want, but I admit it does take another look into the code to properly understand how:

https://docs.rs/rust-htslib/0.23.0/src/rust_htslib/bam/record.rs.html#723

I.e., `as_bytes()` should give you a vector of the decoded bases, but in `u8`(this is done via indexing, which is implemented for the `Seq` struct and should take care of decoding into IUPAC bases via [`DECODE_BASE`](https://docs.rs/rust-htslib/0.23.0/src/rust_htslib/bam/record.rs.html#675)). So all you have to do, is transform the `u8` vector into a string, which you can do with:
```
    println!("{:}", from_utf8(&rec.seq().as_bytes()).unwrap() );
```

For this, you just need to include:
```
use std::str::from_utf8;
```

Hope this helps...

**Comment by PoisonAlien** [comment]
Yes! It works. Thank you :)
