### ISSUE TITLE
Transfer crate to rust-bio team

### ISSUE THREAD

**Issue by johanneskoester** [rust-bio/rust-htslib#14]
This continues the efforts in issue #9 to transfer the ownership of the crate to the rust-bio team.
@christopher-schroeder can you try again to issue the following command:
```
cargo owner --add github:rust-bio:owners
```
in your rust-htslib clone?

**Comment by johanneskoester** [comment]
Any updates on this? It would be time for a new release again.

**Comment by christopher-schroeder** [comment]
sorry, I still got the 
failed to add owners to crate rust-htslib: api errors: only members of github:rust-bio:owners can add it as an owner
error message

**Comment by christopher-schroeder** [comment]
but nevertheless I published the new version

**Comment by johanneskoester** [comment]
Thanks! Can you go to the rust-bio main view, click on teams and then on the join button for the owners team?

**Comment by christopher-schroeder** [comment]
It did work, I would also suggest to not rename the Owners Team

**Comment by johanneskoester** [comment]
Ah, great!
