### ISSUE TITLE
Is it possible to extract unmapped reads from a indexed BAM?

### ISSUE THREAD

**Issue by ifiddes-10x** [rust-bio/rust-htslib#151]

**Comment by johanneskoester** [comment]
An indexed bam as well has a plain read method (you have to do `use rust_htslib::bam::Read`). With that, it should be possible, but you need to walk though the entire file I guess. Maybe there is a better way to do this via fetch. It should be possible to find a solution in the original htslib codebase.

**Comment by TyberiusPrime** [comment]
I just learned how to do this: fetch_str("*").

**Comment by juliangehring** [comment]
@TyberiusPrime This will unfortunately only give you unaligned reads where no coordinate has been set (typically the case for e.g. read pairs where both read and mate don't align). For read pairs where the mate aligns, it is a common convention to use the coordinates of the mapping partner. See the [SAM specs](https://samtools.github.io/hts-specs/SAMv1.pdf) which recommends:

> For a unmapped paired-end or mate-pair read whose mate is mapped, the unmapped read should
> have RNAME and POS identical to its mate.

If one wants all unaligned reads, one would have to iterate through all reads and check the flag, as @johanneskoester mentioned.

**Comment by TyberiusPrime** [comment]
Good catch, though the @ifiddes-10x  didn't mention whether their data is paired or not.

fetch_str(".") should iterate over all reads.

**Comment by juliangehring** [comment]
It doesn't really matter if it is single or paired read data - the above was just a common example. Looking at the flag in a BAM entry is unfortunately the only reliable entry to determine if a read is unmapped, the position fields are only indicative.

**Comment by TyberiusPrime** [comment]
You're absolutely right, the spec states on page 6: "• Bit 0x4 is the only reliable place to tell whether the read is unmapped.".

"*" will only work iff the reads have been sorted to the end of the file, and this only happens if they have no contig assigned.
