### ISSUE TITLE
read api changes broke my code :(. / while let Ok(_) = read() no longer works

### ISSUE THREAD

**Issue by TyberiusPrime** [rust-bio/rust-htslib#162]
This is mostly a cautionary tale for others:

The alloc-less way to iterate over reads used to be based on 
```fn read(&mut self, record: &mut record::Record) -> Result<(), ReadError>```
which has recently (version 0.25) converted to
``` fn read(&mut self, record: &mut record::Record) -> Result<bool> ```

Accordingly, the calling code most be adjust from 
```while let Ok(_) = bam.read(&mut record)```
to 
```while let Ok(true) = bam.read(&mut record)```

Otherwise you run into an endless loop.

Unfortunatly, the Ok(_) pattern is valid rust even on the new types so no compiler errors.

This has been a fun hour of doubting my sanity.

**Comment by johanneskoester** [comment]
I am so sorry, I did not anticipate that side-effect.

**Comment by brainstorm** [comment]
Wouldn't it make sense to keep (or rollback to) `Result<(), ReadError>` in rust-htslib instead of `Result<bool>` which is not very Rust-idiomatic (common?) AFAIK?

I can [see other functions](https://github.com/rust-bio/rust-htslib/blob/master/src/bcf/mod.rs#L45) with this gotcha and it can indeed be a trap for young #rust-htslib players like me, IMHO :/

**Comment by sjackman** [comment]
Does it every return `Ok(false)`, and if so, what does that mean? If it never returns `Ok(false)` then I agree that this change would best be rolled back to instead return `Result<()>`.

**Comment by slazicoicr** [comment]
I am also not fond of the `Result<bool>` approach (user has to look up what true/false means), but neither do I think `Result<()>` was ideal (user has to look up which error means the end of file). I think the use of `Option` is the most explicit and clear representation: `Option<Result<()>>`. Am I getting any reads and if so, was there an error in parsing the read?

This would informative compile time errors for anyone who used the `while let Ok(_) = bam.read(&mut record)` pattern. It would require minor modification:

```
while let Some(res) = bam.read(&mut record) {
    // deal with res if not Ok, otherwise use record
}

**Comment by brainstorm** [comment]
@sjackman I've not done a exhaustive checking on all functions and what they return, but the return type that @slazicoicr proposes makes sense to me.

Tangentially, it could also help getting https://github.com/rust-bio/rust-htslib/pull/163 out the door. Those changes might produce a breaking release, which I'd be fine with if it significantly improves the ease of use and coherence of this crate, IMHO.

@slazicoicr Would you be interested in leading that? It's good timing since we're heading towards a #244 and we might potentially include a few changes while we are at it...

@johanneskoester @dlaehnemann What's your take on this?

**Comment by dlaehnemann** [comment]
Jep, the suggestion by @slazicoicr definitely looks like the most Rust-idiomatic to me.

And Rust `Option`'s [don't seem to have any memory overhead](https://stackoverflow.com/questions/16504643/what-is-the-overhead-of-rusts-option-type), but I couldn't find anything on runtime. Does anybody have pointers, or know?

**Comment by brainstorm** [comment]
To be honest I would aim at getting as close as possible to Noodles API:

https://github.com/zaeleus/noodles/tree/master/noodles-bam/examples

His Rust clean room implementation of the format standards really is the kind of DX I would like to see in rust-htslib... not to mention the opportunity to move from one crate to the other without the "API switch cognitive burden" would be a big plus, IMO.

**Comment by slazicoicr** [comment]
Looking at Noodles API, I don't see the pre-allocation approach (https://docs.rs/rust-htslib/0.32.0/src/rust_htslib/bam/mod.rs.html#269-286) that this issue discusses. Noodles API seems to use the iterator approach only (https://docs.rs/rust-htslib/0.32.0/src/rust_htslib/bam/mod.rs.html#292-294). Given this, is the `Option` approach still the consensus for rust-htslib pre-allocation approach?

**Comment by brainstorm** [comment]
Thanks for raising those points @slazicoicr, good ones! Unless there are good reasons to do so (mainly performance and memory consumption), in general I would favor iterators over pre-allocs... so while refactoring the return types, it might make sense to also explore issue #163 in parallel?

**Comment by slazicoicr** [comment]
Return type refactor at #257

**Comment by juliangehring** [comment]
> Looking at Noodles API, I don't see the pre-allocation approach (https://docs.rs/rust-htslib/0.32.0/src/rust_htslib/bam/mod.rs.html#269-286) that this issue discusses.

Noodles has the preallocation approach here: https://github.com/zaeleus/noodles/blob/master/noodles-bam/src/reader.rs#L149-L195

**Comment by slazicoicr** [comment]
Good catch. With Noodles approach, the original issue (`Ok(_)` silently failing) still stands. I still feel `Option` approach is more explicit in differentiating end of file vs error, but there is something to be said about a consistent API across implementations. Noodles approach hampers error handling in the `while let` approach, as `while let Ok(r) = bam.read_record(&mut record)` doesn't work well for handling errors (not the end of the world, as using `loop` would allow that).

**Comment by zaeleus** [comment]
`Result<bool>` may be the most reasonable choice here, given what `sam_read1` returns. `Result<bool>` isn't _too_ unusual, particularly when the number of bytes read will likely never be used. This return type can be seen in, e.g., [`csv::Reader::read_record`].

`Option<Result<()>>` seems to be optimizing for the `while let` use case, which I consider the wrong control flow construct if errors need to be handled. For an idiomatic example, take [`std::io::BufRead::read_line`]. Using `while let`, there is no way to handle the error variant.

```rust
while let Ok(bytes_read) = reader.read_line(&mut buf) {
    if bytes_read == 0 {
        break;
    }

    // ...
}
```

Any other variant must be handled separately; thus, this is why matching in a `loop` is common.

```rust
loop {
    match reader.read_line(&mut buf) {
        Ok(0) => break,
        Ok(_) => { /* ... */ },
        Err(e) => panic!("{:?}", e),
    }
}
```

[`csv::Reader::read_record`]: https://docs.rs/csv/1.1.3/csv/struct.Reader.html#method.read_record
[`std::io::BufRead::read_line`]: https://doc.rust-lang.org/std/io/trait.BufRead.html#method.read_line

**Comment by TyberiusPrime** [comment]
The read API is read-the-manual territory anyway.
So I'd like we stop bike shedding this and refrain from another breaking change.

**Comment by brainstorm** [comment]
I would honestly prefer to implement some guardrails to avoid the issue you had originally at the start of this thread?: https://github.com/rust-bio/rust-htslib/issues/162#issue-513919367

I'd be comfortable bumping rust-htslib to a new major version to get this right, so that others don't fall on this trap without having to go cover-to-cover reading on the docs? :-S

**Comment by TyberiusPrime** [comment]
The guardrails will only help with implementations that came from before 0.25.

It's a limited set I suppose and I'm not sure it's worth breaking every implementation again
(even if in a won't compile manner this time) for a niche api.

**Comment by dlaehnemann** [comment]
Hmmm, I understand your worries about bike-shedding. But we should come to some conclusion, here.

I see the arguments for keeping it as is (`Result<bool>`) as:
* changing anything, [would again be a breaking change](https://github.com/rust-bio/rust-htslib/issues/162#issuecomment-691617478) and possibly in [several of the modules](https://github.com/rust-bio/rust-htslib/issues/162#issuecomment-581247062)
* [`Result<bool>` is being used elsewhere](https://github.com/rust-bio/rust-htslib/issues/162#issuecomment-691571917), so is not uncommon
* spending time here is time we don't spend on other issues

I see the arguments for changing this to `Option<Result<>>`:
* `Option<Result<>>` is less likeley to fail silently (the compiler enforces handling of `None`)
* allows for the `while let Some(record)` pattern
* this pattern could be easier to pick up for people new to Rust

I would still be in favour of changing to `Option<Result<>>`, especially as this means that the compiler can check for correct usage -- which I think is generally the most Rusty way...
If we opt for this, we should then implement it wherever we currently have the `Result<bool>` pattern.
But I also don't mind keeping the `Result<bool>`, should more people tend towards this, as it can handle all cases. We could still envisage the change for a later API-breaking update.

Any quick votes? Or further arguments? Let's move this forward!

**Comment by TyberiusPrime** [comment]
My vote is on 'drop the read api all together'. 
It's a c-ish workaround for a non allocating Iterator.

RcRecords #265 is just as fast in practice, and I'm going to use it even if I have to have it living in an extension

With #261 just being accepted, we could even throw away the two-step API that we inherited from htslib (fetch, then iterate) for a one stop 
 * .records(FetchDefinition) (for when you need copies of the reads anyhow)
* .rcrecords(FetchDefinition) (for when you don't) 
* .pileup(FetchDefinition)
 API. 

That would be a breaking change I'd consider ok :).

**Comment by slazicoicr** [comment]
This can be closed as API has changed.
