### ISSUE TITLE
Trying to write an uncompressed BCF instead writes as a VCF

### ISSUE THREAD

**Issue by felix-clark** [rust-bio/rust-htslib#167]
Initializing a `bcf::Writer` with `uncompressed = true` and `format = bcf::Format::BCF` results in output identical to that if `format` is instead specified to be `bcf::Format::VCF`. This is likely the result of [this line](https://docs.rs/rust-htslib/0.26.0/src/rust_htslib/bcf/mod.rs.html#599), which specifies the file open mode for an uncompressed BCF as `"wu"`. It should probably instead be `"wbu"` as specified in [the comments for hts_open()](https://github.com/samtools/htslib/blob/develop/htslib/hts.h#L469).

If my interpretation is correct and it helps, I can try to make a pull request for this minor change.

**Comment by johanneskoester** [comment]
Thanks for the PR!
