### ISSUE TITLE
update to htslib 1.10

### ISSUE THREAD

**Issue by dlaehnemann** [rust-bio/rust-htslib#183]
htslib has recently had a big release with lots of bugfixes and new stuff, for example APIS for SAM headers and AWS S3:
<https://github.com/samtools/htslib/releases/tag/1.10>

This will very likely require a bunch of changes, so this is an issue to track any work on updating this wrapper to the new version.

**Comment by brainstorm** [comment]
Shall we close this issue in favour of https://github.com/rust-bio/rust-htslib/pull/184? I would like to have efforts on this focused on the PR since it might confuse people wanting to help out and seeking comments in both places... I would be confused :-S

**Comment by dlaehnemann** [comment]
Yes, sure. This issue was merely meant to track any discussion before a PR exists or in case there would be mutliple PRs. But with your major efforts over at PR #184 progressing so fast and cited here, no reason to keep this issue open!
