### ISSUE TITLE
Parental leave until end of February, please be patient :-)

### ISSUE THREAD

**Issue by johanneskoester** [rust-bio/rust-htslib#186]
Hi folks, I am on parental leave until end of February.
Hence, I won't have the chance to look into your bug reports and PRs until then. 

Of course, you are all invited to do mutual reviews :-)! 

Thanks a lot for your patience. 
Johannes

**Comment by brainstorm** [comment]
Welcome back! :)

**Comment by johanneskoester** [comment]
Thanks!
