### ISSUE TITLE
create htslib outputs in cargo $OUT_DIR

### ISSUE THREAD

**Issue by pmarks** [rust-bio/rust-htslib#19]
the current build.rs script creates the build outputs in the src directory, which prevents cargo from cleaning them up on 'cargo clean'.  This prevents users of rust-htslib from getting a truly clean build after 'cargo clean'.  This can cause issues e.g. when building from the same .cargo directory on different linux versions.

The recommended practice (if possible) is to have build.rs call the Makefile such that the outputs go to env::var("OUT_DIR"), which is then managed by cargo.  Discussion & example change to build.rs:
https://github.com/rust-lang/cargo/issues/2573
https://github.com/julienw/openzwave-rust/commit/ebc2ad4681902003ebb825733b1bdf8367eb42ae

**Comment by johanneskoester** [comment]
Yes, I definitely want this as well. I am open to PRs, but I will also try to do it myself as soon as I find some time.

**Comment by johanneskoester** [comment]
And sorry for the really late response. As you know, usually I try to react much faster :-)!
