### ISSUE TITLE
Major performance regression 0.28+

### ISSUE THREAD

**Issue by veldsla** [rust-bio/rust-htslib#195]
I see a major impact on performance for version 0.28 and 0.29

I use the bam.records() iterator (owned records) and bam.set_threads(4). (Linux)
As an example for .027 I see
```
real	0m4,055s
user	0m13,759s
sys	0m0,501s
```

With 0.2[89] I get
```
real	0m41,202s
user	0m53,027s
sys	0m0,926s
```
I think the change was mostly the htslib upgrade?

Edit: htslib upgrade was before. Diffing .27 and .28 showed me this:
https://github.com/rust-bio/rust-htslib/blob/b12b3632d253c32cf7df4020914dfe71789d0467/src/bam/mod.rs#L273 in the read record function. (it's also in the `IndexedReader` at line 467)

Cloning the header into every record is probably not a good idea.

Final edit: Confirmed. Removing the `record.set_header` still compiles and performance is restored. Not sure what or who depends on this header being set though...

**Comment by johanneskoester** [comment]
Thanks a lot for reporting. My fault, I remembered this to be a shallow clone. But looking into the code shows me that it is actually not a shallow one. I will have a look into a fix.

**Comment by johanneskoester** [comment]
Should be fixed with commit 3fa020d. Thanks again!

**Comment by johanneskoester** [comment]
I will create a new release today.

**Comment by veldsla** [comment]
Thanks, I can confirm HEAD is as performant as before.
