### ISSUE TITLE
iterating over records in seeked regions

### ISSUE THREAD

**Issue by PoisonAlien** [rust-bio/rust-htslib#197]
I apologize in advance if this is not the right place to ask this. 
I have trouble accessing `records` in bam file after seeking to a genomic region. Below is an example command following the example from [docs](https://docs.rs/rust-htslib/0.30.0/rust_htslib/):

```rust
fn main(){
	let bam_file: String = String::from("test.bam");
	let chr: String = String::from("chr1");
	let start: u64 = 33881016;
	let end: u64 = 33881116;
	let region: String = String::from("chr1:33881016-33881116");


	let mut bam = bam::IndexedReader::from_path(&bam_file).unwrap();

	//Using fetch
	let tid = bam.header().tid(chr.as_bytes()).unwrap();
	bam.fetch(tid, start, end).unwrap();
	for r in bam.records(){
		let r = r.unwrap();
		println!("{:?}", r); //Prints nothing
	}

	//using fetch_str
	bam.fetch_str(region.as_bytes()).unwrap();	
	for r in bam.records(){
		let r = r.unwrap();
		println!("{:?}", r); //Prints nothing
	}
}
```
In both the cases (with `fetch` or `fetch_str`), iterator does not output anything. Am I doing anything wrong here? Thanks!

**Comment by juliangehring** [comment]
Your code is working fine for me with v0.30.0.
Have you checked that BAM file actually has reads overlapping your region of interest, e.g. with `samtools view test1.bam chr1:33881016-33881116`?

**Comment by PoisonAlien** [comment]
Thank you so much, yes you are correct indeed! 
I have a typo. Its supposed to be `chr11` and not `chr1`. Wasted whole day, and I blame it on work from home.
