### ISSUE TITLE
Bam can no longer be opened from  http / ftp locations

### ISSUE THREAD

**Issue by veldsla** [rust-bio/rust-htslib#20]
The nice thing about htslib tools is that they also open web locations. This also used to be possible with rust-htslib but after 13f8c44 this is no longer the case. Why not rely on the result of the bgzf_open call to decide if a file exists?

**Comment by johanneskoester** [comment]
I wasn't aware of that. Absolutely, this should be implemented differently!

**Comment by johanneskoester** [comment]
Fixed in PR #21.
