### ISSUE TITLE
64 bit BAM-tag values are written to 32 bit fields

### ISSUE THREAD

**Issue by jch-13** [rust-bio/rust-htslib#209]
According to the BAM specs (https://samtools.github.io/hts-specs/), numeric values in auxiliary fields ("tags") are stored as 32 bit values. However, `htslib` returns 64 bit values when _reading_ those fields, even though they are stored as 32 bit values (`int64_t bam_aux2i(...)` and `double bam_aux2f(...)`), which is probably the reason why `rust-htslib`'s  `Aux::Integer(i64)` and `Aux::Float(f64)` enum representations of those fields correspondingly wrap 64 bit values.
https://github.com/rust-bio/rust-htslib/blob/3fa020da8b04de5d8323f1bc0e6332f3bf154408/src/bam/record.rs#L762-L769

Hence, when _writing_ BAM tags with the `bam::Record::push_aux(..., value: &Aux<'_>)` method, 64 bit values get written to 32 bit fields (quite explicitly by setting the offset to 4 bytes in the `push_aux(...)` method), which leads to misbehavior.
https://github.com/rust-bio/rust-htslib/blob/3fa020da8b04de5d8323f1bc0e6332f3bf154408/src/bam/record.rs#L601-L619

As far as I can see, `htslib` supports a `d` (double) type to store 64 bit floating point values (which I cannot find in the specs), but there does not seem to be a 64 bit equivalent for integers.

Edit: The float case can simply be solved by adding a `Aux::Double(f64)` variant and changing the existing `Aux::Float(f64)` to `Aux::Float(f32)` (API-breaking), but I'm not quite sure how to approach the integer case ergonomically (and preferably checked at compile-time). I think none of these approaches are overly satisfying:
- Adding a 32 bit enum variant and reject 64 bit values at runtime in `push_aux(...)`
- Changing the enum variant to `Aux::Integer(i32)` and down-cast automatically when reading BAM tags
- Adding another enum just for writing BAM tags

**Comment by dlaehnemann** [comment]
Good catch. And this does look tricky to fix. From what I can see, the following functions are the ones publicly available for first getting the pointer to an AUX tag's data and then getting out an integer value (all the other possible types follow below, but I skip them to keep the code rendered here to a minimum):

https://github.com/samtools/htslib/blob/develop/htslib/sam.h#L1357-1376

So, `bam_aux2i` will always return an `int64_t`, no matter what the original type of the stored data was (`i8`, `i16`, ...). How this happens, becomes clear from this htslib-internal code:

https://github.com/samtools/htslib/blob/9de45b72b3a3f3df7a0ffda3554aeab1f6da50ba/sam.c#L3673-3694

Thus, while I would have thought that the optimal implementation would distinguish between these different types of integers that the specs allow, this becomes a little difficult with functions like `bam_aux2i` that returns an `int64_t` no matter what and does not pass on the original type.

But from what I understand of the code over in PR #170, you parse out the type manually with pointer arithmetic and then use `bam_aux2i` and the other htslib functions anyways. This might actually be the way to go for input parsing.
Another alternative might be to implement better and more fine-grained versions of the `bam_aux2` functions in Rust, i.e. including a `bam_aux2` function for every individual type allowed, maybe using the following functions that `bam_aux2i` uses internally (only displaying the first here, there are respective functions for all allowed types):

https://github.com/samtools/htslib/blob/fc431ebc252166f47f798e20954c5ccf8be83a8c/htslib/hts_endian.h#L212-224

This would also solve a further problem: As was [pointed out in the gamgee project](https://github.com/broadinstitute/gamgee/issues/97), there is ambiguity in the return value of 0 for `bam_aux2i` and `bam_aux2f`. It can signify an error (meaning an invalid type specification was found) -- or the actual value of `0`. If we implement our own functions, we can simply avoid this problem.

However, the optimal solution would probably be to fix the `bam_aux2` functions in htslib itself, either letting it pass through the type or returning the correct type, and making sure there is no ambiguity in the return value. We could try and suggest that change over there and then use the improved functions.

And once we have more fine-grained types of AUX tags, including stuff like `Aux::I16(i16)` and `Aux::U16(u16)`, putting tags into records should become clearer. Just for reference, this is the function to use:

https://github.com/samtools/htslib/blob/9de45b72b3a3f3df7a0ffda3554aeab1f6da50ba/htslib/sam.h#L1434-1446

And that is its implementation:

https://github.com/samtools/htslib/blob/9de45b72b3a3f3df7a0ffda3554aeab1f6da50ba/sam.c#L3372-3402

From what I understand, the different Integer types would then simply amount to different `len`s passed into that function? But I'm not absolutely sure. But I hope these thoughts help to bring this discussion forward.

**Comment by jch-13** [comment]
Thanks for the detailed response! 
>  Another alternative might be to implement better and more fine-grained versions of the bam_aux2 functions in Rust, i.e. including a bam_aux2 function for every individual type allowed, maybe using the following functions that bam_aux2i uses internally

I think implementing the `bam_aux2` function set for all supported types in Rust and extending the `Aux` enum might be the best option currently. Upstream `htslib` is probably not going to change its API soon, but if they are, we'll be able to simply switch to wrapping the improved upstream functions.

> From what I understand, the different Integer types would then simply amount to different lens passed into that function? But I'm not absolutely sure. But I hope these thoughts help to bring this discussion forward.

That's what I understand too. This function is only called from `rust-htslib` by `push_aux` which can easily be extended to support the missing types.

Thank you!

PS: The `d` f64 type is not part of the specs, but is has been around in `htslib` for some time (https://github.com/samtools/htslib/issues/974#issuecomment-554280237). So I'm not sure if we should allow to write this type, but it might be necessary to support reading it. Depends on whether there are files using it in the wild.

**Comment by jch-13** [comment]
> Another alternative might be to implement better and more fine-grained versions of the bam_aux2 functions in Rust, i.e. including a bam_aux2 function for every individual type allowed, maybe using the following functions that bam_aux2i uses internally (only displaying the first here, there are respective functions for all allowed types):

https://github.com/samtools/htslib/blob/6b72368c97a234ceebdc89c8806199585d9706b3/htslib/hts_endian.h#L212-L224

Unfortunately, `le_to_i16()` and other functions from `htslib/hts_endian.h` are not part of the public API, so we can not simply re-implement `bam_aux2i` using them.

As an alternative, do you think casting of the wide values returned by e.g. `bam_aux2i` to the actual width of the types (according to the specification) would suffice as a solution? This way, we'd be able to use public `htslib` functions without losing accuracy IMO.

> This would also solve a further problem: As was pointed out in the gamgee project, there is ambiguity in the return value of 0 for bam_aux2i and bam_aux2f. It can signify an error (meaning an invalid type specification was found) -- or the actual value of 0. If we implement our own functions, we can simply avoid this problem.

This problem could still avoided since `0` is only returned to indicate an error if the type passed to a `bam_aux2x` function does not match x which can be avoided on the `rust-htslib` API side.

**Comment by dlaehnemann** [comment]
Argh, I had feared that while ruminating over this issue. Casting to the right type and checking that it returns the right type sound like a good way forward. I guess it will mean implementing good tests and fiddling around a bit to figure out what exactly comes out of the `htslib` functions. But it's definitely worth trying!
