### ISSUE TITLE
Problem when publishing

### ISSUE THREAD

**Issue by johanneskoester** [rust-bio/rust-htslib#218]
@brainstorm @pmarks I have problems to publish a new version. What I get is

```
Caused by:
  failed to select a version for `hts-sys`.
    ... required by package `rust-htslib v0.31.0 (/home/johannes/scms/rust-htslib/target/package/rust-htslib-0.31.0)`
versions that meet the requirements `^1.10` are: 1.10.2

the package `rust-htslib` depends on `hts-sys`, with features: `bindgen` but `hts-sys` does not have these features.
 It has a required dependency with that name, but only optional dependencies can be used as features.
```

Which is kind of weird, because bindgen is in fact an optional dependency.
Do you have an idea what might be wrong?

**Comment by pmarks** [comment]
I think it must be selecting an older version of hts-sys.  I we should probably keep the hts-sys version in the main Cargo.toml exactly synced to the version of hts-sys.

**Comment by johanneskoester** [comment]
Thanks!
