### ISSUE TITLE
Getting array-type (type B) auxiliary data

### ISSUE THREAD

**Issue by hisakatha** [rust-bio/rust-htslib#227]
This is a feature request.
Currently, function [aux](https://github.com/rust-bio/rust-htslib/blob/e979e3446ecc5d18b2dc518c0dcffb1cbdde324d/src/bam/record.rs#L573) ignores array-type (type B) auxiliary data. It would be appreciated if array-type data could be retrieved using rust-htslib.

**Comment by jch-13** [comment]
I'm working on this as part of fixing #209 .

**Comment by jch-13** [comment]
BAM array support has been introduced in 029a612284ac4e3498f3a718da786cef1762192a :)

**Comment by dlaehnemann** [comment]
Thanks @jch-13 !
