### ISSUE TITLE
Count alt-allele dosage in multi-sample VCF/BCF

### ISSUE THREAD

**Issue by weinstockj** [rust-bio/rust-htslib#228]
Hi Rust-htslib developers, 

I'm looking for the best way to get the alt-allele dosage for a given variant in a multi-sample vcf/bcf. For example, for a bi-allelic SNP, I'd like to convert the vector of genotypes to a vector of 0 (Hom-ref), 1 (Het), or 2 (Hom-alt). Phase is ignored in this calculation. 

At the moment, I am doing something like (which counts alt-alleles and stores in a Hashmap):

```
 let genotypes = record.genotypes().unwrap();
 for s in 0..sample_count {
                let mut alt = 0;
                if genotypes.get(s)[0] == bcf::record::GenotypeAllele::Unphased(1) {
                    alt += 1;
                }
                if genotypes.get(s)[1] == bcf::record::GenotypeAllele::Unphased(1) {
                    alt += 1;
                }

                if map.contains_key(&samples[s]) {
                    *map.entry(&samples[s]).or_insert(0) += alt;
                } else {
                    map.insert(&samples[s], alt);
                }
  }

```
Storing these as a hashmap vs vector is just a detail. Curious if this it the recommended approach for working with unphased genotypes in a vcf/bcf. 

Thanks for developing rust-htslib,
Josh

**Comment by juliangehring** [comment]
I'm not sure if there is a recommended or best way of achieving this. Here is one alternative suggestion - maybe this is helpful if you also want to handle non-bi-allelic variants:

```rust
let gts = record.genotypes().unwrap();
for sample_index in 0..sample_count {
    // for each sample
    for gta in gts.get(sample_index).iter() {
        // for each allele
        match gta.index() {
            Some(0) => n_ref[sample_index] += 1, // reference allele
            Some(_) => n_alt[sample_index] += 1, // alt allele
            None => break,                       // missing allele
        }
    }
}
```

**Comment by weinstockj** [comment]
got it - that is helpful. Thanks!

**Comment by brainstorm** [comment]
Closing in favor of #198 ;)

**Comment by brainstorm** [comment]
Reopening, since this issue was very specific and well written/formulated, worth adding to the official docs, thanks both!

**Comment by brainstorm** [comment]
@edmundlth working on this 💪🏻
