### ISSUE TITLE
Can't build scHLAcount from 10XGenomics. Points to rust-htslib which points to unavailable rust-bio/htslib.git

### ISSUE THREAD

**Issue by ppapadopoulos** [rust-bio/rust-htslib#229]
Hello, I'm trying to build scHLAcount from 10Genomics. It uses rust-htslib at a certain revision. That revision references
rust-bio/htslib.git which is unavailable to me.   

it looks like all of your releases of rust-htslib prior to 0.26.1 reference this repo.  (So nothing that references an older version
can build.    It looks like scHLAcount is referencing your 18072e0faf909ed19da4d1226a35c239a4b4292e, committed about
1 year ago.  Just prior to your 0.25 release (which is 10 months old).

==> Is it possible for you to make the repo visible again? Perhaps with a note that it is outdated?

**Here's what I see when trying to build their software (which references your git repo)**

in the checked-out repository  (scHLAcount)
```
scHLAcount-0.1.0/git/checkouts/rust-htslib-ac43057d2e45ec9e/18072e0  
and in that checkout is the htslib submodule definition
scHLAcount-0.1.0/git/checkouts/rust-htslib-ac43057d2e45ec9e/18072e0/.gitmodules
and it's contents are:
[submodule "htslib"]
        path = htslib
        url = https://github.com/rust-bio/htslib.git     <=== This is what I CANNOT see. even as an authenticated user in github
```

There is no htslib repo under rust bio that is visible to me.   So the submodule checkout fails when I try to build.

Here's the full output that I get. 

```
$ export CARGO_HOME=$(pwd)
$ cargo build
    Updating crates.io index
    Updating git repository `https://github.com/10XGenomics/rust-debruijn`
    Updating git repository `https://github.com/10XGenomics/rust-pseudoaligner.git`
    Updating git repository `https://github.com/rust-bio/rust-htslib.git`
    **Updating git submodule `https://github.com/rust-bio/htslib.git`**
error: failed to get `rust-htslib` as a dependency of package `sc_hla_count v0.1.0 (/tmp/scHLAcount-0.1.0)`

Caused by:
  failed to load source for dependency `rust-htslib`

Caused by:
  Unable to update https://github.com/rust-bio/rust-htslib.git?rev=18072e0faf909ed19da4d1226a35c239a4b4292e#18072e0f

Caused by:
  failed to update submodule `htslib`

Caused by:
  failed to fetch submodule `htslib` from https://github.com/rust-bio/htslib.git

Caused by:
  failed to authenticate when downloading repository
attempted to find username/password via git's `credential.helper` support, but failed

Caused by:
  failed to acquire username/password from local configuration

```

**Comment by tedil** [comment]
I think the issue has been resolved in 10XGenomics/scHLAcount (their build was pointing to a certain old git revision of rust-htslib and is now pointing at a more recent *release*)
