### ISSUE TITLE
Hackathon (and/or Docathon)

### ISSUE THREAD

**Issue by brainstorm** [rust-bio/rust-htslib#244]
In the same vibe as https://github.com/rust-bio/rust-bio/issues/276 opened by @tedil, I think we need to have this library's bioinformatics "hello worlds" sorted out as best as we can to facilitate fast use and uptake.

## Getting started

Before you start, check out the [contribution guidelines](https://github.com/rust-bio/rust-bio#contribute). For example, you might want to [officially join the `rust-bio` team](https://github.com/rust-bio/rust-bio/issues/27) to be able to create branches off the main repository. And for actually improving the docs, have a look at the brand new [documentation guidelines](https://github.com/rust-bio/rust-bio#documentation-guidelines).

To track where improvements are needed most and who is tackling what, [we have created a project board](https://github.com/rust-bio/rust-htslib/projects/1). Feel free open new issues for whatever you think is lacking documentation. Please **be specific** on what's lacking or what you would like to see. i.e:

Good issue title:  "Write doc example on retrieving BAM headers with a regexp"
Not so good:       "Docs need improvement"

From that project board, choose one of the issues, move it to `In progress` and assign yourself. Once you're done with it, open a pull request and request a review from one of the other hackathoners. Once the pull request is merged, simply close the issue -- the project board should automagically 🧙🏽‍♀️ move it to `Done`.

## Jump into our Discord server

https://discord.gg/rssQABT

## When

Will start on **14th September 2020**.

**Comment by vsoch** [comment]
Is anyone working on something well scoped, with clear direction / instruction that I could help with? I'm relatively new to rust so I'm not ready to do something entirely solo yet, but I think I could help with some direction.

**Comment by brainstorm** [comment]
Hey @vsoch, first of all welcome over here :)

# Async draft spec of a task

I would love for someone like you, with a fresh look at this project, to go over the first page of the official docs and try to run the examples described there:

https://docs.rs/rust-htslib/0.32.0/rust_htslib/

For instance, somebody pointed out that [just printing a BAM file header](https://github.com/rust-bio/rust-htslib/issues/246) (bioinfo hello world) was "nondescriptive" (confusing?) in the docs. 

More specifically the goal would be to have a printout like this one (using `samtools` cli, just so you have a third party "control" tool outside rust-htslib):

```shell
rust-htslib % samtools view -H test/test.bam
@SQ	SN:CHROMOSOME_I	LN:15072423
@SQ	SN:CHROMOSOME_II	LN:15279345
@SQ	SN:CHROMOSOME_III	LN:13783700
@SQ	SN:CHROMOSOME_IV	LN:17493793
@SQ	SN:CHROMOSOME_V	LN:20924149
@PG	ID:samtools	PN:samtools	VN:1.10	CL:samtools view -H test/test.bam
```

But the goal would obviously be to see that programmatically with `rust-htslib` instead. Makes sense?

# **Sync** draft spec of tasks

Plus help and feedback from maintainers over discord: https://discord.gg/rssQABT ... different timezones, so it can converge to async comms but I just wanted to provide several channels for you to give feedback if you feel stuck or lost ;)

# Labelling/scoping of tasks

You just raised a very valid point when asking for help: **we should be better defining/describing the tasks that need to be done!**

As a newcomer what would you like to see?: **More explicit labeling of issues (i.e "good first issue")** on the issue tracker? Or just **better description of steps/TODO's** within those tasks? Both, something else?

Thanks! :)

**Comment by brainstorm** [comment]
There's also https://github.com/rust-bio/rust-htslib/issues/251 which should be a fairly good first issue to fix (testing `Bam::Read` against `test/bam2sam_out.sam`) if one prefers more code and testing over docs ;)
