### ISSUE TITLE
Behaviour with S3 cross region is different between Rust binding lib and regular htslib

### ISSUE THREAD

**Issue by andrewpatto** [rust-bio/rust-htslib#269]
Using htsfile to do a basic AWS S3 access of a file in us-west-2. This works.

`AWS_PROFILE=sandbox htsfile -vvvvvvvvvv -h s3://igv-demo-bucket-west/TD01-GV1001.merged.bam`

we can see in the logs the initial connection to us-east-1 that generates a 400 error, which is then parsed for redirect and corrected..

```
[D::init_add_plugin] Loaded "knetfile"
[D::init_add_plugin] Loaded "mem"
[D::init_add_plugin] Loaded "libcurl"
[D::init_add_plugin] Loaded "gcs"
[D::init_add_plugin] Loaded "s3"
[D::init_add_plugin] Loaded "s3w"
*   Trying 52.218.219.51...
* TCP_NODELAY set
* Connected to igv-demo-bucket-west.s3.amazonaws.com (52.218.219.51) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: C=US; ST=Washington; L=Seattle; O=Amazon.com, Inc.; CN=*.s3.amazonaws.com
*  start date: Nov  9 00:00:00 2019 GMT
*  expire date: Mar 12 12:00:00 2021 GMT
*  subjectAltName: host "igv-demo-bucket-west.s3.amazonaws.com" matched cert's "*.s3.amazonaws.com"
*  issuer: C=US; O=DigiCert Inc; OU=www.digicert.com; CN=DigiCert Baltimore CA-2 G2
*  SSL certificate verify ok.
> GET /TD01-GV1001.merged.bam HTTP/1.1
Host: igv-demo-bucket-west.s3.amazonaws.com
User-Agent: htslib/1.10.2 libcurl/7.64.1
Accept: */*
Authorization: AWS4-HMAC-SHA256 Credential=AKIAZWW**********/20200921/us-east-1/s3/aws4_request,SignedHeaders=host;x-amz-content-sha256;x-amz-date,Signature=d92309656430279bea7a12c2f4f0913ef0ed8eeee7e6e4999d7c96646d4816bc
x-amz-date: 20200921T073536Z
x-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855

< HTTP/1.1 400 Bad Request
< x-amz-request-id: E9B187E7679D1667
< x-amz-id-2: JYMOBbx5Tc1q9hI5nRIESHZNyVzHpzq552pQUCrzuz9uB6DIw+7KnnQeohOpyONJXlf9d/pNC/k=
< Content-Type: application/xml
< Transfer-Encoding: chunked
< Date: Mon, 21 Sep 2020 07:35:43 GMT
< Connection: close
< Server: AmazonS3
<
* Closing connection 0
* Hostname igv-demo-bucket-west.s3.amazonaws.com was found in DNS cache
*   Trying 52.218.219.51...
* TCP_NODELAY set
* Connected to igv-demo-bucket-west.s3.amazonaws.com (52.218.219.51) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: C=US; ST=Washington; L=Seattle; O=Amazon.com, Inc.; CN=*.s3.amazonaws.com
*  start date: Nov  9 00:00:00 2019 GMT
*  expire date: Mar 12 12:00:00 2021 GMT
*  subjectAltName: host "igv-demo-bucket-west.s3.amazonaws.com" matched cert's "*.s3.amazonaws.com"
*  issuer: C=US; O=DigiCert Inc; OU=www.digicert.com; CN=DigiCert Baltimore CA-2 G2
*  SSL certificate verify ok.
> GET /TD01-GV1001.merged.bam HTTP/1.1
Host: igv-demo-bucket-west.s3.amazonaws.com
User-Agent: htslib/1.10.2 libcurl/7.64.1
```

The same via Rust htslib

```rust
unsafe {
        htslib::hts_set_log_level(10);
    }

    let bam = "s3://igv-demo-bucket-west/TD01-GV1001.merged.bam";
    {
        clear_aws_env();

       // redacted for github issue
        env::set_var("AWS_ACCESS_KEY_ID", "AKIAZWW***********");
        env::set_var("AWS_SECRET_ACCESS_KEY", "YYYYYYYYYY");

        println!("{}", bam_header_readable(String::from(bam)).await);
    }
```

```
[D::init_add_plugin] Loaded "knetfile"
[D::init_add_plugin] Loaded "mem"
[D::init_add_plugin] Loaded "libcurl"
[D::init_add_plugin] Loaded "s3"
[D::init_add_plugin] Loaded "s3w"
[D::setup_auth_data] no embedded ids in s3 path so using env and found AWS_ACCESS_KEY_ID
[D::setup_auth_data] was decided to be dns_compliant=1 and using sigver=4
[D::s3_open_v4] s3_open_v4
[D::s3_open_v4] s3_open_v4 read mode
[D::s3_open_v4] url is https://igv-demo-bucket-west.s3.amazonaws.com/TD01-GV1001.merged.bam
[D::v4_auth_header_callback] v4_auth_header_callback
*   Trying 52.218.247.59:443...
* Connected to igv-demo-bucket-west.s3.amazonaws.com (52.218.247.59) port 443 (#0)
* ALPN, offering http/1.1
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* ALPN, server did not agree to a protocol
* Server certificate: *.s3.amazonaws.com
* Server certificate: DigiCert Baltimore CA-2 G2
* Server certificate: Baltimore CyberTrust Root
> GET /TD01-GV1001.merged.bam HTTP/1.1
Host: igv-demo-bucket-west.s3.amazonaws.com
User-Agent: htslib/1.10.2 libcurl/7.71.1-DEV
Accept: */*
Authorization: AWS4-HMAC-SHA256 Credential=AKIAZWW*********/20200921/us-east-1/s3/aws4_request,SignedHeaders=host;x-amz-content-sha256;x-amz-date,Signature=2d1fa0de2ce89ecc46313c212ad111f14e76453d6585d0b172167d7116cedc59
x-amz-date: 20200921T074118Z
x-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855

* Mark bundle as not supporting multiuse
< HTTP/1.1 400 Bad Request
< x-amz-request-id: BW7VBR1J1R2G4SFM
< x-amz-id-2: n7JM95GvawlvzssvIrAiXAlmXXo8IyoBHL8iSROy7/OeIjvZZezWwFYgHeTwaSovIVgCcO+ljdA=
< Content-Type: application/xml
< Transfer-Encoding: chunked
< Date: Mon, 21 Sep 2020 07:41:25 GMT
< Connection: close
< Server: AmazonS3
< 
[D::handle_400_response] handle 400 response
* Closing connection 0
```

The corresponding htslib code where it finishes.

```rust
static int handle_400_response(hFILE *fp, s3_auth_data *ad) {
    // v4 signatures in virtual hosted mode return 400 Bad Request if the
    // wrong region is used to make the signature.  The response is an xml
    // document which includes the name of the correct region.  This can
    // be extracted and used to generate a corrected signature.
    // As the xml is fairly simple, go with something "good enough" instead
    // of trying to parse it properly.

    char buffer[1024], *region, *reg_end;
    ssize_t bytes;
    hts_log_debug("handle 400 response");

    bytes = hread(fp, buffer, sizeof(buffer) - 1);
    if (bytes < 0) {
        return -1;
    }
    buffer[bytes] = '\0';
    hts_log_debug("400 response \"%s\"", buffer);
```

The hread() here seems to be reading nothing. Can we think of anything in the configuration of libcurl etc? that might be the reason this code path that seems to work in the general htslib tools doesn't work in the Rust build?

**Comment by andrewpatto** [comment]
In the case where the default (us-east-1) also is the region for the bucket then all is good.. and in the case where the AWS region is set to the same region as the bucket then that also works - so there are lots of very common AWS scenarios that do work. Its just as we started to get to some of the edge cases that we are noticing this fail.

**Comment by andrewpatto** [comment]
Some more debugging. The region redirect content *is* definitely returned from AWS

```
[D::recv_callback] libcurl recv_callback: of <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AuthorizationHeaderMalformed</Code><Message>The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'us-west-2'</Message><Region>us-west-2</Region><RequestId>27F12DF815CDB4ED</RequestId><HostId>6tg3imSczsb/wrmbOEBrurabnPH3ZTKckMx5N4GK7Wtd1QYVZSpb7uCo2XXIMZyp85L2/XwnIDk=</HostId></Error> bytes
```

But I can only get access to this in the hfile_libcurl recv_callback.

By the time the outer hfile_s3.c tries to read this XML the read fails. Could it be AWS S3 being super aggressive about closing connections? In some experimentation in another project I had a bug where S3 would close connections on me - but the issue would only be triggered when doing connections from Australia -> US east coast (round trip latency enough to make AWS initiate a close?)

**Comment by brainstorm** [comment]
@andrewpatto Great findings and thanks for the exaplanation! I'll be looking at this issue later today. First I want to finish up my AWS SAM Rust branch migration: https://github.com/brainstorm/htsget-aws/commit/22344cb10aa691541856f2fae76794a0233c93d5

I've found out that [they improved it massively since I last tried](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/building-custom-runtimes.html) and it allows for productive local lambda invokes (without waiting for long docker instantiation & co)... way better than CDK for this usecase, even better if it allows for local debugging, WIP...

**Comment by andrewpatto** [comment]
Ok - all solved I think. Turns out this is a libcurl/htslib interaction - that has been fixed in upstream htslib

https://github.com/samtools/htslib/commit/c7c7fb56dba6f81a56a5ec5ea20b8ad81ce62a43

The problem is triggered for us in the 400 response from S3 when needing to do a region redirect - which S3 immediately closes the connection. This would trigger the above discussed bug between libcurl/htslib. All it needs in htslib is a check to see if the connection is closed and return 0 bytes available (EOF) rather than turning this into an error and failing.

**Comment by brainstorm** [comment]
Argh, sorry @andrewpatto, I should have seen that coming since I had this same discussion over twitter a few weeks ago:

https://twitter.com/jomarnz/status/1298181891946942466?s=20

I think that the best course of action would be to `git submodule update` our `htslib` to a more recent commit (since there are no more recent official releases)... I would even check out to upstream's `develop`, but I doubt the rest of maintainers would be happy with that [(even if there are substantial improvements in multiple fronts if you look at the changelog from 1.10.2 onwards)](https://github.com/samtools/htslib/compare/fd0f89554459b78c07303e2c8a42acacd6851b46..80161279b755d83df6e0dbc52942f625df414452).

@dlaehnemann @pmarks, do you think it would be ok to bump the submodule to a non-tagged (released) version of upstream's `htslib`?

**Comment by dlaehnemann** [comment]
From what I've seen in discussions over at htslib, [a version 1.11 release is imminent](https://github.com/samtools/htslib/pull/929#issuecomment-694799309). I don't know how urgent this is for you, but maybe you can bridge the remaining days (or weeks?) with working on a branch that points to a non-tagged version? And as soon as the new release is there, make the switch on the `master` branch, here, and ship it with the next rust-htslib release.

**Comment by dlaehnemann** [comment]
I wasn't aware that imminent currently meant hours...

https://github.com/samtools/htslib/releases/tag/1.11

**Comment by andrewpatto** [comment]
I was going to reply and say I had no time pressure - and that weeks was fine.. but hours is fine too..

**Comment by brainstorm** [comment]
Let's get this update rolling, exciting!
