### ISSUE TITLE
Inconsistent build behaviour for some .c files in hts-sys/htslib

### ISSUE THREAD

**Issue by andrewpatto** [rust-bio/rust-htslib#271]
This came about from some of my s3 bug hunting - I was editing `hts-sys/htslib/hfile_s3.c` to add some debug traces - all was fine in that whenever I made changes to that file a `cargo build` would cause a C compile. (btw this was being used from a project that selected the `s3` feature).

As I dug deeper at some point I needed to add some debug traces to `hts-sys/htslib/hfile.c` - which to my surprise *does not* trigger any rebuild after editing - but only when the `s3` feature is enabled.

I took a brief look at the `build.rs` and `hfile.c` is definitely listed as `cargo:rerun-if-changed=` - so it feels like it should work - but I am certainly not an expert in rust build systems. 

(the shortest path to recreate for me is - just tested (macos))

- checkout rust-htslib
- `cargo build --features s3`
- `vi hts-sys/htslib/hfile.c` (add syntax error at top of file)
- `cargo build --features s3` (this will succeed when it shouldn't)
- `cargo build` (this will fail with a syntax error)
- `vi hts-sys/htslib/hfile_s3.c` (add syntax error at top of file)
- `cargo build --features s3` (this will fail as expected)

So it appears the s3 feature disables dependency checking for `hfile.c` - though its not like `hfile.c` is an optional feature - it is the core file for making all the other file reader plugins work.

@brainstorm suggested I ping @nlhepler and @pmarks as experts in the build.rs..

**Comment by andrewpatto** [comment]
Possible difference, some files seem to be compiled with an absolute path from the 'out' folder where they had been copied

```
warning: In file included from /Users/andrew/Work/user/rust-htslib/target/debug/build/hts-sys-92a52fd409e8b9de/out/htslib/cram/open_trace_file.c:82:
warning: /Users/andrew/Work/user/rust-htslib/target/debug/build/hts-sys-92a52fd409e8b9de/out/htslib/htslib/hfile.h:271:35: warning: comparison of integers of different signs: 'long' and '
```

whereas `hfile_s3.c` seems to have a relative path (in terms of warning messages) 

```
warning: htslib/hfile_s3.c:455:56: warning: unused parameter 'response' [-Wunused-parameter]
warning: static int redirect_endpoint_callback(void *auth, long response,
warning:                                                        ^
```

**Comment by brainstorm** [comment]
Thanks Andrew! Can you refer to the actual branch/project you are currently building and its `Cargo.toml`? The "s3" feature (IIRC) should be enabled in your source project as features, i.e:

```toml
rust-htslib = { git = "https://github.com/rust-bio/rust-htslib.git", features = ["s3", "static"] }
```

OTOH the way you supply `--features` to cargo should work as well, I reckon :-S

**Comment by andrewpatto** [comment]
So the minimal reproducible experiment thing I did above is just self building `rust-htslib` (so just checked out master and doing a cargo build directly in the project)

**Comment by pmarks** [comment]
@andrewpatto thanks for the report - I see the issue, working on a fix.
