### ISSUE TITLE
README pileup example code confusion

### ISSUE THREAD

**Issue by wwood** [rust-bio/rust-htslib#28]
Hi,

Thanks for writing rust-htslib, I'm finding it very helpful. However, one thing - when iterating through a pileup, I found the example code in README.md slightly misleading.

I have a made up bam file (I could provide it if that is helpful), here is a region shown with `samtools mpileup`:
```
random_sequence_length_500      31      T       19      ...................     ~~~~~~~~~~~~~~~~~~~
random_sequence_length_500      32      A       19      .-1G.-1G.-1G.-1G.-1G.-1G.-1G.-1G.-1G.-1G.-1G.-1G.-1G.-1G.-1G.-1G.-1G.-1G.-1G    ~~~~~~~~~~~~~~~~~~~
random_sequence_length_500      33      G       19      *******************     ~~~~~~~~~~~~~~~~~~~
random_sequence_length_500      34      T       22      ...................^].^].^].    ~~~~~~~~~~~~~~~~~~~~~~
```
When I run the below code trivially modified from the example code
```rust
extern crate rust_htslib;
use rust_htslib::bam;
use rust_htslib::prelude::*;

fn main() {
    let bam = bam::Reader::from_path(&"/tmp/test_member.fa.bam").unwrap();

    // pileup over all covered sites
    for p in bam.pileup() {
        let pileup = p.unwrap();
        println!("{}:{} depth {}", pileup.tid(), pileup.pos(), pileup.depth());

        for alignment in pileup.alignments() {
            match alignment.indel() {
                bam::pileup::Indel::Ins(len) => println!("Insertion of length {}", len),
                bam::pileup::Indel::Del(len) => println!("Deletion of length {}", len),
                _ => println!("Base {}", alignment.record().seq()[alignment.qpos()])
            }
        }
    }
}
```
I get the below. Notice that at position 31 (position 32 in the pileup above), it reports a deletion of 1. However, the actual base `A` hasn't been deleted, it is the next base G which has been deleted. In position 32, it reports `T`s when actually it is a `*` i.e. I would naively read this as `T*TT` when it is actually `TA*T`.
```
...
0:30 depth 19
Base 84
Base 84
Base 84
Base 84
Base 84
Base 84
Base 84
Base 84
Base 84
Base 84
Base 84
Base 84
Base 84
Base 84
Base 84
Base 84
Base 84
Base 84
Base 84
0:31 depth 19
Deletion of length 1
Deletion of length 1
Deletion of length 1
Deletion of length 1
Deletion of length 1
Deletion of length 1
Deletion of length 1
Deletion of length 1
Deletion of length 1
Deletion of length 1
Deletion of length 1
Deletion of length 1
Deletion of length 1
Deletion of length 1
Deletion of length 1
Deletion of length 1
Deletion of length 1
Deletion of length 1
Deletion of length 1
0:32 depth 19
Base 84
Base 84
Base 84
Base 84
Base 84
Base 84
Base 84
Base 84
Base 84
Base 84
Base 84
Base 84
Base 84
Base 84
0:33 depth 22
Base 84
Base 84
Base 84
Base 84
Base 84
Base 84
Base 84
...
```
I'm not quite sure where issue lies here, maybe just with my misunderstanding?. But on a practical level, is there some way to, given a `rust_htslib::bam::pileup::Alignment` struct, determine that the current base should be `*`? The only way that I can see for doing this outside of rust-htslib is to track individual reads and that seems a little messy.

Thanks. ben.

**Comment by johanneskoester** [comment]
Thanks. Indeed, something seems to go on here. Could you provide the bam file so that I can test it locally?

**Comment by wwood** [comment]
Sure, I put the whole thing bam file and all at https://github.com/wwood/rust-htslib-example

**Comment by johanneskoester** [comment]
Samtools mpileup reports an indel at the last position before it occurs. Hence, at position 31, you would rather report the base with qpos, and also say that there will be a deletion next. Rust-Htslib just wraps around what is provided by samtools here. Does this make more sense?

**Comment by wwood** [comment]
OK, I'm not very familiar with the samtools API, so I'll take your word for it. But I suppose as a user of rust-htslib, it would be better if at position 33 a `*` would be reported, rather than the next base `T`. Otherwise, I have to track each read for deletions coming up, which is a bit of a pain. Do you follow? For instance, pysam does provides methods for testing for deletions:
```python
import pysam
samfile = pysam.AlignmentFile("ex1.bam", "rb" )
for pileupcolumn in samfile.pileup("chr1", 100, 120):
    print ("\ncoverage at base %s = %s" %
           (pileupcolumn.pos, pileupcolumn.n))
    for pileupread in pileupcolumn.pileups:
        if not pileupread.is_del and not pileupread.is_refskip:
            # query position is None if is_del or is_refskip is set.
            print ('\tbase in read %s = %s' %
                  (pileupread.alignment.query_name,
                   pileupread.alignment.query_sequence[pileupread.query_position]))
```

Also, if the behaviour isn't changed then I'd say the README could be clarified to reflect this.

Of course, this is just my opinion, I've not contributed anything beyond opening the issue..

Thanks for the quick response.

**Comment by johanneskoester** [comment]
Let me know if that suits your needs. If not, please reopen this issue. Thanks a lot, this really helped to improve the library!

**Comment by wwood** [comment]
Those changes suit me perfectly. Thanks.
