### ISSUE TITLE
Will there be a new release of hts-sys soon to fix the linked issue?

### ISSUE THREAD

**Issue by sstadick** [rust-bio/rust-htslib#283]
https://github.com/samtools/htslib/pull/1143

It looks like this is still a problem with the latest rust-htslib release. Trying to build causes the same issue described in htslib. 

If I specify `rust-htslib = 0.35.0`, compiling fails at hts-sys. But if I specify `rust-htslib = { git = "https://github.com/rust-bio/rust-htslib", branch = "master" }` it compiles and works just fine.

**Comment by fxwiegand** [comment]
A [new version](https://crates.io/crates/rust-htslib/0.35.2) with the fixes just released. You can specify `rust-htslib = "0.35.2"` and should be good to go.

**Comment by sstadick** [comment]
Awesome! Thanks @fxwiegand!
