### ISSUE TITLE
Access read group tag for BAM reads

### ISSUE THREAD

**Issue by jlboat** [rust-bio/rust-htslib#287]
I'm sure this is probably straightforward, but I can't figure out how to access the read group information on a per-read basis within a BAM file. I can get it from the header, but I can't determine how to use aux or any other record method to get that info. I realize this might change after issues #170 and #209 are implemented, but what's the current approach for this?

**Comment by jch-13** [comment]
Assuming the read group information is stored in `RG:Z:` fields, it can be accessed via `bam::record::Record::aux(b"RG")`. This method should return a `Aux::String(<&'a [u8]>)`.

**Comment by jlboat** [comment]
Thank you! I thought I had tried that, but it's working for me now so I'm not complaining.
