### ISSUE TITLE
Accessing reference name in BAM record

### ISSUE THREAD

**Issue by bluenote-1577** [rust-bio/rust-htslib#288]
I'm wondering if there is a way to get the RNAME (reference name) field for a specific read? Apologies if I'm just missing something but I can't find anything in the bam::record::Record documentation on this. 

Thanks for developing this awesome library by the way!

**Comment by sitag** [comment]
@bluenote-1577 https://github.com/rust-bio/rust-htslib/blob/master/src/bam/record.rs#L304-L307 should do it. See https://docs.rs/rust-htslib/0.35.2/rust_htslib/bam/record/struct.Record.html#method.qname

**Comment by bluenote-1577** [comment]
@sitag I'm asking about the reference name, not the read name, i.e. which reference the specific read is mapped to. Unless I'm misunderstanding, the function you linked seems like it returns the read name?

**Comment by sitag** [comment]
@bluenote-1577  from this https://github.com/rust-bio/rust-htslib/blob/master/src/bam/record.rs#L86-L95 - you likely want tid
if i recall right, you may have to look up the reference name from the header using tid

**Comment by bluenote-1577** [comment]
@sitag Thanks for your help. I got it to work by using the tid2name function from HeaderView. 

As a side note, this may be a useful function to have in Record because it's not super obvious to me (as someone who hasn't messed around with htslib before) :).

**Comment by sitag** [comment]
@bluenote-1577 I agree. Send a pull request. Though I think since it would need a header reference anyway (the actual record does not contain the rname string), it probably just needs to be documented. Maybe as `recipes for htsrust`

**Comment by ebioman** [comment]
Hi sorry to hijack this but I have trouble understand on what HeaderView actually works.
Does somebody have an example how to access the chromosome/target ID with that ? 
The [official doc](https://docs.rs/rust-htslib/0.36.0/rust_htslib/bam/struct.HeaderView.html?search=) leaves me a bit clueless

**Comment by dlaehnemann** [comment]
Thanks for providing the example code. If you can find some extra time and feel like contributing to `rust-htslib`, putting these into doctests for the respective functions would be great. This would both test the relevant code AND automagically appear on `docs.rs` as example usage that others can simply copy. The relevant code section to add these doctests would be around here:

https://github.com/rust-bio/rust-htslib/blob/029a612284ac4e3498f3a718da786cef1762192a/src/bam/mod.rs#L1247

And the `rust-bio` README.md contains all the relevant links that should get you started on writing doctests:
https://github.com/rust-bio/rust-bio#documentation-guidelines
