### ISSUE TITLE
writing sam output

### ISSUE THREAD

**Issue by sitag** [rust-bio/rust-htslib#29]
I am looking to see if it was possible to write uncompressed sam output. I see that `bam_write1` is used from https://github.com/rust-bio/rust-htslib/blob/4ee0f403c60b566a1e840122c37517e57e8b3767/src/bam/mod.rs#L381 while `sam_write1` is never used outside of where it's defined. So it looks like there is no way to write sam output without making direct calls to sam_write1? Would it be possible to get a template to write sam as well?

**Comment by sitag** [comment]
I think an addition method on `Writer` would do it?


    pub fn sam_write(&mut self, record: &record::Record) -> Result<(), WriteError> {
        if unsafe { htslib::sam_write1(self.f, record.inner) } == -1 {
            Err(WriteError::Some)
        }
        else {
            Ok(())
        }
    }

**Comment by johanneskoester** [comment]
SAM is not really a format that is needed I think. It is always more efficient to simply write BAM. Of course, I'd accept pull requests in this direction though. API-wise it would be most reasonable to have a flag when constructing the writer that tells it to be sam.

**Comment by sitag** [comment]
Yes, SAM is not the best; it's just that some downstream code needs SAM. It seemed a waste to fire up a samtools instance compressing and then decompressing. I will look to see if that's all it takes.

**Comment by johanneskoester** [comment]
Solved with PR #31. Thanks again!
