### ISSUE TITLE
Capped number of reads on pileup?

### ISSUE THREAD

**Issue by garcia-nacho** [rust-bio/rust-htslib#298]
Hi,

I  have been comparing different methods to get reads from a bam file and it seems that  rust_htslib only can get up to 8018 reads (or at least pileup.depth() can get only up to 8018, I haven't checked if the actual number of reads is higher), while other tools show much deeper coverage suggesting that the library is capped. Is this intentional? For most of the analyses 8018 is probably more than enough but I am just wondering if there is a reason for that. 

Coverage obtained with pileup.depth
![image](https://user-images.githubusercontent.com/22105380/112735676-21124a80-8f4e-11eb-80b4-7926633a80ed.png)

Coverage obtained with IRanges
![image](https://user-images.githubusercontent.com/22105380/112735789-4f902580-8f4e-11eb-8324-bcb8a5a88fbd.png)

Coverage obtained with IRanges capped on 8018 to show similarities with rust_htslib
![image](https://user-images.githubusercontent.com/22105380/112735812-74849880-8f4e-11eb-9355-f6ff91268c6f.png)

Best

**Comment by veldsla** [comment]
htslib/samtools have always capped coverage at 8000x, but it is configurable and also exposed in rust-htslib:
https://docs.rs/rust-htslib/0.36.0/rust_htslib/bam/pileup/struct.Pileups.html#method.set_max_depth

**Comment by garcia-nacho** [comment]
Thanks!!!
