### ISSUE TITLE
Slow regex(?) parsing in CigarString::try_from()

### ISSUE THREAD

**Issue by mrvollger** [rust-bio/rust-htslib#299]
Hi,

I have been trying to learn rust by playing around with bioinformatics formats and rust-htslib has been great for that, so thanks!

I needed a function to turn a string slice into a cigar string from a PAF file for a whole genome alignment and I used [CigarString::try_from(&str)](https://docs.rs/rust-htslib/0.36.0/src/rust_htslib/bam/record.rs.html#1124-1168) to do it. I found that it took over a minute to parse a cigar string with ~200k elements which seemed slow. 

I have a feeling that maybe the regex crate is slowing this down because I cannot see anything else in the function that could be slowing it down. 

I rewrote the function without the regex and now it is much faster < 1s. But I am not a rust expert and my tests are not extensive so I didn't feel justified in making a pull request. But here is my code if it is of interest. 

Best,
Mitchell

```rust
/// Create a CigarString from given str.
/// # Example 
/// ```
/// use rustybam::paf;
/// use rust_htslib::bam::record::*;
/// use rust_htslib::bam::record::CigarString;
/// use rust_htslib::bam::record::Cigar::*;
/// use std::convert::TryFrom;
/// use std::str::FromStr;
/// let cigars = vec!["10M4D100I1102=", "100000M20=5P10X4M"];
/// for cigar_str in cigars{
///     let my_parse = paf::cigar_from_str(cigar_str).expect("Unable to parse cigar");
///     let hts_parse = CigarString::try_from(cigar_str).expect("Unable to parse cigar");
///     assert_eq!(my_parse, hts_parse);
/// }
/// ```
/// TODO add IO errors 
pub fn cigar_from_str(text: &str) -> Result<CigarString, std::io::Error> {
    let bytes = text.as_bytes();
    let mut inner = Vec::new();
    let mut i = 0;
    let text_len = text.len();
    while i < text_len {
        let mut j = i;
        while j < text_len && bytes[j].is_ascii_digit(){
            j += 1;
        }
        let n = u32::from_str(&text[i..j]).expect("Bam parse error");
        let op = &text[j..j+1];
        inner.push(match op {
            "M" => Cigar::Match(n),
            "I" => Cigar::Ins(n),
            "D" => Cigar::Del(n),
            "N" => Cigar::RefSkip(n),
            "H" => Cigar::HardClip(n),
            "S" => Cigar::SoftClip(n),
            "P" => Cigar::Pad(n),
            "=" => Cigar::Equal(n),
            "X" => Cigar::Diff(n),
            op => panic!("Unable to parse {} as cigar op", op)
        });
        i = j + 1;
    }
    Ok(CigarString(inner))
}
```

**Comment by dlaehnemann** [comment]
This actually sounds like a great speedup and a quick look at the code (and the doctest) suggests that this is probably the better version. Would you like to work that into a pull request, exchanging the function that you link to (while keeping its signature the same)?

Maybe add the test cases you provide in the doctest to the existing tests at the end of `record.rs` in a first pull request (to test the old code), and then change the function and check that the tests still pass. I'd be glad to review a PR.

And should you feel adventurous (and have more time on your hands), there are a bunch of restrictions on CIGAR strings we currently do not validate (for example `H` can only be the first or last operation) and it would be nice to add checks for those. The details are in the SAM specs:

https://github.com/samtools/hts-specs/blob/9d0bd8645fe777ffb61e6666e13b69e707c234f9/SAMv1.tex#L518-L549

**Comment by mrvollger** [comment]
Cool. I'll see if I can put something together next weekend.
