### ISSUE TITLE
bam::Record end_pos calculation

### ISSUE THREAD

**Issue by veldsla** [rust-bio/rust-htslib#32]
It seems https://github.com/rust-bio/rust-htslib/blob/master/src/bam/record.rs#L93 doesn't consider the cigar element `Cigar::Del` to contribute to the end position. `Cigar::RefSkip` does count and is basically the same operation. 
This would also make the test at https://github.com/rust-bio/rust-htslib/blob/master/src/bam/mod.rs#L702  incorrect as the first 5 reads span 101bp over the reference and read 6 spans 100100bp.

**Comment by johanneskoester** [comment]
Thanks!
