### ISSUE TITLE
Confused with nex Aux functionality

### ISSUE THREAD

**Issue by ebioman** [rust-bio/rust-htslib#328]
Hi
I am sorry if this is a very noob question but I am confused with the new aux functionality as an enum.
Previously I used 
```
let mismatch     =  record.aux(b"NM").unwrap_or(rust_htslib::bam::record::Aux::Integer(0));
let mismatch_2   = mismatch.integer() as i32;
```
In order to get the number of mismatches as an integer for further steps in my program.
Now I understand that I should use accordingly:

```
let mismatch     =  record.aux(b"NM").unwrap_or(rust_htslib::bam::record::Aux::I32(0));
```

But now this is obviously an enum instead and I am really confused how I access now that value
and if I should actually should use the Aux::Integer in that case.
Sorry if really basic question

**Comment by jch-13** [comment]
Hi!
The `Aux::I32` variant is indeed the right choice for `NM:i` fields.
You can use pattern matching to extract values from Enum variants; either by [`match`](https://doc.rust-lang.org/book/ch06-02-match.html)ing on the variants or by using the [`if let`](https://doc.rust-lang.org/book/ch06-03-if-let.html) syntax. 

If there is only one variant you are interested in (like in your example), `if let` is shorter and probably more readable:
```Rust
use rust_htslib::bam::record::Aux;

// "if-let" pattern matching
let mismatch = if let Ok(Aux::I32(nm_i)) = record.aux(b"NM") {
    nm_i
} else {
    0
};
```

**Comment by ebioman** [comment]
Hi @jch-13 
Thanks a lot for the help :) 
Indeed that works great!
Since I am more the `match` guy and have a bit trouble with the above syntax, just here the match version for completeness if somebody later stumbles here:
```
                    let mismatch     = match record.aux(b"NM") {
                        Ok(rust_htslib::bam::record::Aux::I32(nm_i)) => nm_i,
                        _ => 0
                    };
```
