### ISSUE TITLE
Support for BGZF writer?

### ISSUE THREAD

**Issue by jemma-nelson** [rust-bio/rust-htslib#347]
Would it be possible to add support for writing BGZF files? I'm trying to accelerate a small program that both reads and writes Fastq, and it would be cool to support BGZF on both the input and output sides of things, ideally with multi-threading support.

Currently, it looks like only the Reader from htslib is exposed: https://github.com/rust-bio/rust-htslib/blob/master/src/bgzf/mod.rs

If this isn't feasible, totally understand. If it sounds feasible but you don't have the desire to do it, let me know and I can take a stab at putting a PR together.

**Comment by dlaehnemann** [comment]
Contributions are always welcome and I think this is the perfect way to get involved. So feel free to take a stab, looking at the Reader for bgzf and possibly also the writers of the other formats. This is how most of the stuff in rust-htslib comes about...

And while it's great to get more functionality in here, I just want to make you aware of another crate for bioinformatics with native Rust implementations for the most important formats: [noodles](https://github.com/zaeleus/noodles). It also has [BGZF read and write functionality](https://docs.rs/noodles/latest/noodles/bgzf/index.html)

**Comment by jemma-nelson** [comment]
Thanks, I'll try to put a PR together in the next week or so. :)

The noodles project is really impressive! I thought that they didn't support multi-threaded compression but it appears that they do: https://github.com/zaeleus/noodles/issues/17
