### ISSUE TITLE
Question about reference sequence

### ISSUE THREAD

**Issue by nihilee** [rust-bio/rust-htslib#348]
Dear developer, could i get reference seq when loop the pileup of bam file??? i read the doc but have no idea

**Comment by dlaehnemann** [comment]
A BAM file does not contain the reference sequence (only the newer CRAM file format can contain the reference sequence, but it doesn't have to), so you'll have to separately provide the reference sequence as a FASTA file and then use [the template id (chromosome)](https://docs.rs/rust-htslib/0.38.2/rust_htslib/bam/record/struct.Record.html#method.tid) and [the position on that template (chromosome)](https://docs.rs/rust-htslib/0.38.2/rust_htslib/bam/record/struct.Record.html#method.pos) to get to the reference sequence at the mapping position of a sequencing read record.
