### ISSUE TITLE
publishing updated versions to crates.io

### ISSUE THREAD

**Issue by rob-p** [rust-bio/rust-htslib#353]
Hi all,

  Thank you for tagging the new version that fixes the M1 compilation issue!  I was wondering if it is possible for updated versions of this library to be put on crates.io.  The reason I ask is that crates.io [does not allow packages that have non crates.io dependencies](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html).  Thus, while building from a git repo and tagged version works fine for local development or deployment to something like bioconda, it precludes and crate using rust-htslib and requiring a newer version, from being itself put on crates.io.  Is there a strong argument against just pushing the latest tagged version to crates.io as part of the tagging / release process?

Thanks,
Rob

**Comment by jdidion** [comment]
+1

Would love to be able to use mudskipper on mac arch64

**Comment by rob-p** [comment]
Thanks @johanneskoester!  Hopefully we can figure out why the auto-bump in Cargo.toml wasn't working.
