### ISSUE TITLE
fastest way to locate reads which contain specify kemr use rust-htslib?? 

### ISSUE THREAD

**Issue by nihilee** [rust-bio/rust-htslib#359]
dear developer, I want to know is there a faster way to get reads which contain some 38 bases kmer from a large bam use rust-htslib???

my kmer file just like this, all of them are 38 bases:
```
TGCTGGAGTGTCCCAAGAGAGATGCAAAGTGTCTGAAT
CGGAGCAGCGGAGAGTCTAACTGGAGGGCCGGTGCGTG
CCGTGAGGCGGAGCAGTGCAGAGCCTACCTGGAGGGCA
GCTGAGAGCCTACCGGGAGGGCACGTGCGTGGAGTGGC
GGCCGCGGGGAGCCCCGCTTCATCGCAGAGGGCTACGT
...
```

I used a hashset to store these kmer, and loop the bam like this:
```
let mut record = bam::Record::new();
while let Some(_) = bam.read(&mut record) {
    for c in record.seq().as_bytes().windows(38){
        if s.contains(c){
            out.write(&record).unwrap();
            break
        }
    }
}
```
but it seems works very slow, is there a faster way??

**Comment by veldsla** [comment]
It's not the best, but should also not be awfully slow. Did you run/compile with --release?

For better options check out the [pattern matching](https://docs.rs/bio/0.41.0/bio/pattern_matching/index.html) algorithms in rust-bio.

**Comment by nihilee** [comment]
thank for your advice! yes I used O3 to compile, I will check out the  algorithms , thank you~

**Comment by veldsla** [comment]
Hashing still sounds like a decent approach. The lookups should be fast, the window walker is quite trivial, so most time should be spent in the Hash function. You can switch to a faster hash function (like [AHash](https://docs.rs/ahash/latest/ahash/)) or you could try to make some sort index structure from your kmer set. 

Also -O3 sounds like a C compiler argument, not Rust where you would compile your project (using Cargo) with the --release flag.
