### ISSUE TITLE
Plans to support modified bases (MM and ML tags)? 

### ISSUE THREAD

**Issue by mrvollger** [rust-bio/rust-htslib#362]
Hi there,

Are there plans to add functions that allow rust_htslib to query modified bases (MM and ML tags) similar to [pysam](https://pysam.readthedocs.io/en/latest/api.html?highlight=MM#pysam.AlignedSegment.modified_bases)?

Thanks in advance!
Mitchell

**Comment by mrvollger** [comment]
I wrote the logic for extracting from the `MM` tag into a function [here](https://github.com/mrvollger/fibertools-rs/blob/66b72f8ce9993974740c0e273f360db305ea0719/src/extract.rs#L11-L84), and in my tests the results agree with `pysam`'s `modified_bases_forward`.  But I am not quite confident enough in my rust skills to make it into a PR.

**Comment by michaelJwilson** [comment]
I see MM tags are now supported, but not ML tags?
