### ISSUE TITLE
How to: empty sequence and quality for BAM entries

### ISSUE THREAD

**Issue by ebioman** [rust-bio/rust-htslib#382]
Hi
I am trying to construct some BAM entries for long alignments. For these I dont have and dont want to store at the moment the sequence and quality values.
I found in the `record.rs` code indeed a hint how to do that for the quality:

```rust
    /// Set variable length data (qname, cigar, seq, qual).
    /// The aux data is left unchanged.
    /// `qual` is Phred-scaled quality values, without any offset.
    /// NOTE: seq.len() must equal qual.len() or this method
    /// will panic. If you don't have quality values use
    /// `let quals = vec![ 255 as u8; seq.len()];` as a placeholder that will
    /// be recognized as missing QVs by `samtools`.
```
This works well for me with the quality when constructing my entry with :
```rust
        let seq = vec![ 255 as u8; match_length.try_into().unwrap()];
        let qual = vec![ 255 as u8; match_length.try_into().unwrap()];
```
and following a `record.set()` providing the above. The quality field in the sam is correctly set  to "*". But this seems not to work similarly with the sequence and I get a set of "N"s in the BAM record. 

In the official SAM spec it is though noted that it should be possible

>10. SEQ: segment SEQuence. This field can be a ‘*’ when the sequence is not stored. If not a ‘*’, the length
of the sequence must equal the sum of lengths of M/I/S/=/X operations in CIGAR. An ‘=’ denotes the
base is identical to the reference base. No assumptions can be made on the letter cases.

Any idea how to achieve that ?

**Comment by jts** [comment]
Looking at the code, `record.set()` appears to do the right thing when seq and qual are both empty (`core.l_qseq` is set to 0, which is the right way to represent empty SEQ in BAM). If you pass in empty vectors for seq/qual does it fail?

**Comment by ebioman** [comment]
Oh my....
So with all the issues around I didnt see the obvious solution anymore :D 
Thanks an empty vector for both worked perfectly
