### ISSUE TITLE
faidx file not closed when Reader goes out of scope: Too many open files

### ISSUE THREAD

**Issue by wdecoster** [rust-bio/rust-htslib#390]
Hi,

I have a tool that repeatedly calls `fetch_seq` on a `faidx::Reader::from_path`, and eventually runs into:

```
[E::fai_load3_core] Failed to open FASTA index GCA_000001405.15_GRCh38_no_alt_analysis_set.fa.fai: Too many open files
Segmentation fault (core dumped)
```

I don't see a method to close the file, although the `Reader` instance goes out of scope (when the function ends). So the file seems not closed when the Reader is dropped. Does anyone have an idea to fix this? I'm not sure if it is something I should do, or a change required in rust-htslib, or a problem on the C side.

I saw a very similar problem reported here https://github.com/rust-bio/rust-htslib/issues/365

Thanks!
Wouter

**Comment by johanneskoester** [comment]
Please reopen if the merged PR does not fix the issue.

**Comment by johanneskoester** [comment]
And thanks for reporting!

**Comment by wdecoster** [comment]
I can confirm that solves the problem :-)
