### ISSUE TITLE
Move rust-htslib to rust-bio organization account?

### ISSUE THREAD

**Issue by johanneskoester** [rust-bio/rust-htslib#4]
Hi,
I have just created a rust-bio organization account. What do you think about moving rust-htslib to this account? Should help to build a good community and get more contributors.

**Comment by christopher-schroeder** [comment]
Sure, sounds good.
Well, why hiding it: its more your project, than mine and you are way 
more rust skilled than me.


Am 13.08.2015 um 19:29 schrieb Johannes Köster:

**Comment by johanneskoester** [comment]
Ok, so you have to go to settings and then to "transfer ownership" at the bottom (in the danger zone ;-)). There, you provide rust-bio as target username.

**Comment by johanneskoester** [comment]
Yeah, I might have written more lines, but I would never have started it alone ;-).

**Comment by johanneskoester** [comment]
Hi Christo,
can you transfer soon? I have a bioinformatics application note about Rust-Bio in review and want to submit the final version with correct URLs.

Thanks!

**Comment by christopher-schroeder** [comment]
It tells me "You don’t have admin rights to rust-bio" if I try to transfer

**Comment by johanneskoester** [comment]
Ok, I have provided admin rights to the contributor team. Now it should work.

**Comment by christopher-schroeder** [comment]
Its done, thanks.

**Comment by johanneskoester** [comment]
Great, thanks!
