### ISSUE TITLE
rust-htslib doesn't build with latest nightly: mem::copy_lifetime() is gone

### ISSUE THREAD

**Issue by benwbooth** [rust-bio/rust-htslib#5]
I can't build rust-htslib with the latest nightly build:

```
$ cargo build
    Updating registry `https://github.com/rust-lang/crates.io-index`
 Downloading winapi v0.2.2
 Downloading advapi32-sys v0.1.2
 Downloading rand v0.3.11
 Downloading winapi-build v0.1.1
   Compiling rust-htslib v0.4.1 (file:///Users/bbooth/src/rust-htslib)
src/bam/record.rs:252:38: 252:56 error: unresolved name `mem::copy_lifetime` [E0425]
src/bam/record.rs:252                     Some(Aux::String(mem::copy_lifetime(self, x)))
                                                           ^~~~~~~~~~~~~~~~~~
src/bam/record.rs:252:38: 252:56 help: run `rustc --explain E0425` to see a detailed explanation
error: aborting due to previous error
Could not compile `rust-htslib`.

To learn more, run the command again with --verbose.
```

mem::copy_lifetime appears to have been removed. I'm not sure how what a good replacement for it is.

**Comment by johanneskoester** [comment]
Hi, I fixed it by removing the copy_lifetime, as it is not to be necessary here any more.

**Comment by johanneskoester** [comment]
Christo, can you publish a new release?

**Comment by johanneskoester** [comment]
Alternatively, you can also transfer the ownership of at crates.io to me. The Bioinformatics application note about Rust-Bio has been accepted and - although the paper is not about Rust-Htslib - it would be great to have a new version published before the paper goes online.

**Comment by christopher-schroeder** [comment]
Oh sorry, I missed the ticket overwhelmed by one hundred holiday emails and was sick the last days
I published the version
