### ISSUE TITLE
[Feature Request] Wrappers for samtools sort?

### ISSUE THREAD

**Issue by hillst** [rust-bio/rust-htslib#57]
Dear authors,

I'm working on an application that would require the resulting bam to be sorted. Not a big deal, but I would appreciate if your library supported samtools sort either via the c library or natively. Let me know if you need more information/usecases. If I'm mistaken and you have already implemented this, please let me know!

Best,
Steve

**Comment by johanneskoester** [comment]
As far as I know, sorting is not a function of htslib, but implemented in the samtools interface. Hence, we don't have access to this as it is only available via the CLI. Of course, one could reimplement sorting, but I wonder where the benefit would be comparing to just using samtools.

**Comment by hillst** [comment]
Thanks for the response! Seems like something that might be saved for a pure rust implementation. I'm closing the issue.
