### ISSUE TITLE
Usage section with install instructions missing

### ISSUE THREAD

**Issue by juliangehring** [rust-bio/rust-htslib#61]
The readme currently points to a "Usage" section for getting installations instructions:

> If you only want to use the library, there is no need to clone the repository. Go on to the Usage section in this case.

However, I couldn't find any such section in the repo or the docs. Could you give me a pointer where I would find it, or is it missing?

**Comment by johanneskoester** [comment]
Thanks, I have updated the readme.

**Comment by juliangehring** [comment]
Great, thanks!
