### ISSUE TITLE
Access to SAM header text in BAM header

### ISSUE THREAD

**Issue by holtgrewe** [rust-bio/rust-htslib#64]
Hi, is it possible to access the SAM header text in a `bam:Header`?

Here is what I get with rust-htslib v0.17:

```
error[E0616]: field `header` of struct `rust_htslib::bam::IndexedReader` is private
  --> src/cli/coverage.rs:75:22
   |
75 |         let header = bam_reader.header;
   |                
```

**Comment by holtgrewe** [comment]
Ah, I have to use the `Read` trait...

**Comment by johanneskoester** [comment]
@holtgrewe it is super cool to see that you dive into Rust! I hope you like it! Don't hesitate to ask questions!
