### ISSUE TITLE
bcf::Record.format returns Format that takes ownership of record

### ISSUE THREAD

**Issue by veldsla** [rust-bio/rust-htslib#8]
I'm fairly new to rust (and quite inexperienced), but I noticed that when I used the record.format function I can no longer call any methods on the record. Rust complains
```
cannot borrow `record` as immutable because it is also borrowed as mutable
previous borrow of `record` occurs here; the mutable borrow prevents subsequent moves, 
   borrows, or modification of `record` until the borrow ends
```
The following code triggers the compile error, but the second method can be anything from record
```rust
let mut gtf = record.format(b"GT");
let gt = gtf.integer().ok().expect("Error reading format.");
let mut ff = record.format(b"FREQ");
let f = ff.string().ok().expect("Error reading format.");
```

I think this happens because a mutable reference to the record is stored in the Format struct.

On closer reading this seems also true in Info and I also cannot get two consecutive info tags without the compiler complaining. I wondered why test test suite seemed unaffected but it probably has something to do with the assert macro.

If you change line https://github.com/rust-bio/rust-htslib/blob/master/src/bcf/mod.rs#L179
```rust
assert_eq!(record.info(b"MQ0F").float().ok().expect("Error reading info."), [1.0]);
```
into
```rust
let mq = record.info(b"MQ0F").float().ok().expect("Error reading info.");
```
The test suite doesn't compile and you get lots of lifetime errors and if you split it in two statements the borrow error surfaces.
```rust
let mut mqi = record.info(b"MQ0F");
let mqval = mqi.float().ok().expect("Error reading info.");
```

Am I completely off in how to use the library and just fighting with the borrow checker as the manual puts it?

**Comment by johanneskoester** [comment]
Hi,
.float() actually returns a mutable reference to the floats in the BCF record from HTSlib. As long as you hold that reference, you cannot have another mutable reference on the BCF record. But this is what your code in the first example does, and also your modification in the second example.
This is also why the assetion works: the reference goes out of scope after the assertion, hence everything works fine.

To solve your problem, you need to make sure that your reference to the float goes out of scope before you invoke a method that needs a mutable reference again. For example, you can use blocks or separated functions to achieve this.

Hope this helps,
Johannes

**Comment by veldsla** [comment]
Ok, it took a few tries, but indeed if I create a function like (without any result matchers):
```rust
fn get_freqs(record: &mut bcf::Record) -> Vec<String> {
    let mut format = record.format(b"FREQ");
    let freq = format.string().ok().expect("Error getting freq");
    freq.iter().map(|s| { std::str::from_utf8(s).unwrap().to_string() }).collect()
}
```
I get what I want. It took a while before I used the to_string. When omitted the freq indeed goes out of scope taking the str::from_utf8 which does no allocation with it. I think it's awesome that the compiler catches that and sort of the reason I want to learn more about the language.

Anyway I guess it now works and we can close this issue. A few more examples in the readme would be very welcome. I now get my information from the test suite which was confusing for me.

**Comment by johanneskoester** [comment]
Yes, you are right. We need to extend the documentation.
