### ISSUE TITLE
format.string result is padded with NULL characters

### ISSUE THREAD

**Issue by veldsla** [rust-bio/rust-htslib#9]
Hi,

Still happily messing with the library. I noticed that when string values are in the format fields they are \0 padded to the length of the largest entry. This is probably fine in the C library where the string terminates with a null, but when I convert to a rust String and print it the \0 characters are also printed.
I have a tiny test VCF with 2 lines and see the following debug output when I just convert the &[u8] to a String:
```
Freq sample 0: Some("100%")
Freq sample 1: Some(".\u{0}\u{0}\u{0}")
Freq sample 0: Some(".\u{0}")
Freq sample 1: Some("1%")
```

Should the slice size reduction be performed in the Format.string method or is this also something a client program should handle itself?

**Comment by johanneskoester** [comment]
Hi,
I have just committed some changes that allow immutable access to format and info. In that case, string() should now remove padding zero characters. Can you confirm that it works in the current master branch?

**Comment by veldsla** [comment]
Actually not yet. Although I don't yet understand why.

If I use the `string` method and debug the ouput of the slices for my 2 sample vcf file I get this:
```
debug string val [49, 48, 48, 37]
debug string val [46, 0, 0, 0]
```
The output when I use `string_mut` is:
```
debug string val [49, 48, 48, 37, 46]
debug string val [46]
```
char 46 is the dot (from the missing value of sample 2) and is reported twice.

On second thought. The original method also didn't include the string terminator in the first slice. So the second ffi::CStr::from_ptr reads through both values.

**Comment by johanneskoester** [comment]
Thanks for testing! Can you post the vcf file (e.g. in a code block)? I will have a closer look.

**Comment by veldsla** [comment]
sure:
```
##fileformat=VCFv4.1
##INFO=<ID=ADP,Number=1,Type=Integer,Description="Average per-sample depth of bases with Phred score >= 15">
##INFO=<ID=WT,Number=1,Type=Integer,Description="Number of samples called reference (wild-type)">
##INFO=<ID=HET,Number=1,Type=Integer,Description="Number of samples called heterozygous-variant">
##INFO=<ID=HOM,Number=1,Type=Integer,Description="Number of samples called homozygous-variant">
##INFO=<ID=NC,Number=1,Type=Integer,Description="Number of samples not called">
##FILTER=<ID=str10,Description="Less than 10% or more than 90% of variant supporting reads on one strand">
##FILTER=<ID=indelError,Description="Likely artifact due to indel reads at this position">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##FORMAT=<ID=GQ,Number=1,Type=Integer,Description="Genotype Quality">
##FORMAT=<ID=SDP,Number=1,Type=Integer,Description="Raw Read Depth as reported by SAMtools">
##FORMAT=<ID=DP,Number=1,Type=Integer,Description="Quality Read Depth of bases with Phred score >= 15">
##FORMAT=<ID=RD,Number=1,Type=Integer,Description="Depth of reference-supporting bases (reads1)">
##FORMAT=<ID=AD,Number=1,Type=Integer,Description="Depth of variant-supporting bases (reads2)">
##FORMAT=<ID=FREQ,Number=1,Type=String,Description="Variant allele frequency">
##FORMAT=<ID=PVAL,Number=1,Type=String,Description="P-value from Fisher's Exact Test">
##FORMAT=<ID=RBQ,Number=1,Type=Integer,Description="Average quality of reference-supporting bases (qual1)">
##FORMAT=<ID=ABQ,Number=1,Type=Integer,Description="Average quality of variant-supporting bases (qual2)">
##FORMAT=<ID=RDF,Number=1,Type=Integer,Description="Depth of reference-supporting bases on forward strand (reads1plus)">
##FORMAT=<ID=RDR,Number=1,Type=Integer,Description="Depth of reference-supporting bases on reverse strand (reads1minus)">
##FORMAT=<ID=ADF,Number=1,Type=Integer,Description="Depth of variant-supporting bases on forward strand (reads2plus)">
##FORMAT=<ID=ADR,Number=2,Type=Integer,Description="Depth of variant-supporting bases on reverse strand (reads2minus)">
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	one	two
19	3111939	.	A	AG	.	PASS	ADP=3;WT=0;HET=0;HOM=1;NC=39	GT:GQ:SDP:DP:RD:AD:FREQ:PVAL:RBQ:ABQ:RDF:RDR:ADF:ADR	1/1:24:8:8:2:6:100%:3.4965E-3:31:33:2:0:5:1,2	./.:.:1
19	3113255	.	G	GC	.	PASS	ADP=3;WT=3;HET=1;HOM=0;NC=36	GT:GQ:SDP:DP:RD:AD:FREQ:PVAL:RBQ:ABQ:RDF:RDR:ADF:ADR	./.:.:2	0/1:18:8:8:3:5:1%:1.2821E-2:35:32:3:0:5:2,3
```
I use it bgzipped and tabixed.

I still need to test it without the truncated format lines (which should be perfectly valid for vcf)
Also the number change for ADR is my testing modification.

**Comment by johanneskoester** [comment]
Hi,
there seems to be something wrong with the file. When I display it with bcftools (after applying bgzip and tabix), I cannot see any genotype information. I am pretty sure that you need a dot for each format element, even if the data is not there.

**Comment by veldsla** [comment]
In the VCF spec you can find:

> If any of the fields is missing, it is replaced with the missing value. For example if the FORMAT is GT:GQ:DP:HQ then 0 | 0 : . : 23 : 23, 34 indicates that GQ is missing. Trailing fields can be dropped with the exception of the GT field, which should always be present if specified in the FORMAT field).

So it should be possible. It could of course be an bug in htslilb, but I'm seeing some more strange issues. I'll try to reduce the testcase.

**Comment by veldsla** [comment]
I created a new testvcf without format truncation that appears to work fine with bcftools. format.string still reads the strings from sample 1 and 2 together. string_mut returns even sized \0 padded slices

```
##fileformat=VCFv4.1
##INFO=<ID=S1,Number=1,Type=String,Description="Single INFO string">
##INFO=<ID=N1,Number=1,Type=Integer,Description="Single INFO integer">
##INFO=<ID=F1,Number=1,Type=Float,Description="Single INFO float">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##FORMAT=<ID=FS1,Number=1,Type=String,Description="Single FORMAT string">
##FORMAT=<ID=FN1,Number=1,Type=Integer,Description="Single FORMAT integer">
##FORMAT=<ID=FF1,Number=1,Type=Float,Description="Single FORMAT float">
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	one	two
19	3111939	rs1234	A	AG	.	PASS	S1=string1;N1=1;F1=1.0	GT:FS1:FN1	1/1:LongString1:1	1/1:ss1:2
19	3113255	rs2345	G	GC	.	PASS	S1=string2;N1=2;F1=2.0	GT:FS1:FN1	1/1:LongString2:1	1/1:ss2:2
19	3113259	rs2345	G	GC	.	PASS	S1=string3;N1=3;F1=3.0	GT:FS1:FN1	1/1:.:1	1/1:ss3:2
19	3113262	rs2345	G	GC	.	PASS	S1=string4;N1=4;F1=4.0	GT:FS1:FN1	1/1:LongString4:1	1/1:.:2
19	3113268	rs2345	G	GC	.	PASS	S1=string5;N1=5;F1=5.0	GT:FS1:FN1	1/1:evenlength:1	1/1:veenlength:2
19	3113272	rs2345	G	GC	.	PASS	S1=string6;N1=6;F1=6.0	GT:FS1:FN1	1/1:ss6:1	1/1:longstring6:2
```
string
```
debug string val [76, 111, 110, 103, 83, 116, 114, 105, 110, 103, 49, 115, 115, 49]
debug string val [115, 115, 49]
FS1 0: Some("LongString1ss1")
FS1 1: Some("ss1")
FN1 :0: Some(1)
FN1 :1: Some(2)
```
string_mut
```
debug string val [76, 111, 110, 103, 83, 116, 114, 105, 110, 103, 49]
debug string val [115, 115, 49, 0, 0, 0, 0, 0, 0, 0, 0]
FS1 0: Some("LongString1")
FS1 1: Some("ss1\u{0}\u{0}\u{0}\u{0}\u{0}\u{0}\u{0}\u{0}")
FN1 :0: Some(1)
FN1 :1: Some(2)
```

**Comment by johanneskoester** [comment]
I have committed some fixes to the master branch. For me, your file is now properly parsed. Can you confirm?

**Comment by veldsla** [comment]
Yes, this works for me. I'm going to expand the test case to more values and types because if I remember correctly I also noticed something weird with integers and missing values. Thanks for your help so far!

**Comment by veldsla** [comment]
I found my other issue. In a FORMAT integer field that has number > 1. If you encode the missing values as a single dot the resulting array contains 1 time the missing value (-MAX) en is then padded with -MAX + 1. For example this vcf:

```
##fileformat=VCFv4.1
##INFO=<ID=S1,Number=1,Type=String,Description="Single INFO string">
##INFO=<ID=N1,Number=1,Type=Integer,Description="Single INFO integer">
##INFO=<ID=F1,Number=1,Type=Float,Description="Single INFO float">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##FORMAT=<ID=FS1,Number=1,Type=String,Description="Single FORMAT string">
##FORMAT=<ID=FN4,Number=4,Type=Integer,Description="Multiple FORMAT integer">
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	one	two
19	3114951	rs1234	A	AG	.	PASS	S1=string1;N1=1;F1=1.0	GT:FS1:FN4	1/1:fourall:1,2,3,4	1/1:formissall:.,.,.,.
19	3114952	rs1234	A	AG	.	PASS	S1=string1;N1=1;F1=1.0	GT:FS1:FN4	1/1:fourall:1,2,3,4	1/1:formiss:.
```

returns
```
debug s [1, 2, 3, 4]
debug s [-2147483648, -2147483648, -2147483648, -2147483648]

debug s [1, 2, 3, 4]
debug s [-2147483648, -2147483647, -2147483647, -2147483647]

```

from the get values integer. -MAX  +1 is described in https://github.com/samtools/htslib/blob/develop/htslib/vcf.h#L774 as the end of vector. Floats reports 4 NaN in both cases.

**Comment by johanneskoester** [comment]
Thanks,
I fixed it in the master branch.

**Comment by veldsla** [comment]
Yes thank you. The only minor thing is the inconsistent length of return value compared to float where 4 NaN are returned in the case of a single ".". But I guess you can never blindly assume any number of elements is actually going to be in the format fields.

**Comment by johanneskoester** [comment]
Yes, the thing is that there is no end indicator value for float used. It is just NaN until the end. So we cannot know.

**Comment by johanneskoester** [comment]
Christo, can you publish a new release?

**Comment by johanneskoester** [comment]
I have already increased the version number to 0.5, because I have made some breaking changes to the API.

**Comment by johanneskoester** [comment]
Christo:
in fact, it is now possible to permit publishing by teams. Can you issue the following command:

```
cargo owner --add github:rust-bio:owners
```

in your the rust-htslib clone?

**Comment by christopher-schroeder** [comment]
Hi,
I have published version 0.5, but I cant add the owner:

"failed to add owners to crate rust-htslib: api errors: only members of github:rust-bio:owners can add it as an owner"

**Comment by johanneskoester** [comment]
I have made you an owner. Now it should work :-)

**Comment by christopher-schroeder** [comment]
Nope its the same error message. But maybe we have to wait a few moments for internal updates or something like that

**Comment by johanneskoester** [comment]
It might help if you re-login into crates.io with your github account.

**Comment by christopher-schroeder** [comment]
:-/ I did, but it doesn't change anything. The same message as before

**Comment by johanneskoester** [comment]
Strange, lets just wait a day then :-).

**Comment by christopher-schroeder** [comment]
Yes I agree

**Comment by johanneskoester** [comment]
I am closing this issue now and opening a new one for the cargo issue.
