### ISSUE TITLE
Documentation on bam reader thread safety?

### ISSUE THREAD

**Issue by ctsa** [rust-bio/rust-htslib#90]
Looking through the docs, it is not if I can instantiate a new `bam::IndexedReader` on each thread within a single process -- should that be safe? Thanks!

**Comment by johanneskoester** [comment]
Actually it is thread safe, in the sense that Rust ensures that there cannot be two threads using the same IndexedReader (via the borrow-checking). Also, it ensures that no two threads have write access to the same record. Basically, this enforces you to use one IndexedReader per thread. As these are independent, this is no problem.

**Comment by johanneskoester** [comment]
Chris, may I ask if  Illumina is considering to use Rust? Or is this a private interest?

**Comment by ctsa** [comment]
Thank you both for the additional detail, that is helpful. 

Johannes -

Illumina is a big place, so I can only speak for my relatively small corner here: I try to keep up with potential c++ alternatives, and among these rust is probably getting the greatest focus. The c++ tools my team has released so far have been single-thread/multi-process with a separate python layer (pyflow) handling the scheduling for either single-node or distributed compute cases. As the number of cores/processor keeps going up there is less motivation to support distributed compute for most problems, so I'm looking at more multi-threaded designs, but at the same time would still like to welcome contributions form scientists who are not necessarily card-carrying software engineers. This gives the rust 'concurrency without fear' story a lot of resonance, but there is still a lot of investigation to be done.

One issue I'm trying to work through is the learning curve of replacing inheritance-based idioms from c++ with trait-based schemes (and to a lesser degree trying to transition away from exceptions). I'm curious if you've found that contributors to rust-bio coming from c++/java/c# style languages have extensively struggled with these types of transitions?

**Comment by johanneskoester** [comment]
Great to hear. About the learning curve when coming from C++-like: In general, I think it should be easiest for such devs, because many things are more straightforward (memory management, thread safety, package management, high-level features and external library use). It might be harder for people coming from scripting languages. Yes, one has to think a bit different in terms of delegation vs. inheritance. Actually, @holtgrewe might be able to give you additional insight here: he was in a C++ oriented lab during his thesis.

**Comment by ctsa** [comment]
Thanks for your perspective on the transition. I'll go ahead and close the issue given that my original question is answered.

**Comment by holtgrewe** [comment]
Hm, I guess it depends where you are coming from. If you are coming from something like Java 6 or "OOP style only C++ emulating Java" then Rust requires to learn new paradigms and think in them. If you are coming from modern C++, you are disappointed by how slowly C++ language is evolving and adapting to other language's features then Rust can feel as a natural upgrade. The borrow checker is more useful than annoying but I found the explicit life times somewhat hard to grasp. Besides this, I like how more "modern" language features are now making it in more and more "mainstream" (read languages with non-niche adaption) languages e.g., functional programming, pattern matching etc.

Besides this, the compiler is incredibly good in terms of error messages, the package management at least as good as for modern Python (read: excellent), tooling is constantly improving, and the community is exceptionally friendly and helpful.

Feel free to drop me a line (email is on my profile) if you have any questions.

**Comment by ctsa** [comment]
Thanks! I suppose I may be guilty of 'c++ emulating java' to some degree. I too have been impressed with many details of the language and the tooling infrastructure. It's the gotcha's that only start to show up 10,000 lines into a project that I'm more worried about -- projects like rust-bio and ripgrep have been helpful in getting some insight on these risks. I will definitely reach out if something comes up.
