### ISSUE TITLE
Process for upgrading htslib

### ISSUE THREAD

**Issue by juliangehring** [rust-bio/rust-htslib#96]
Just out of curiosity: What steps are needed to upgrade the newer releases of htslib (e.g. from 1.6 to 1.8)? Is updating the htslib submodule and running `cargo test` sufficient to check that the bindings still work with newer versions, or does this generally require more manual checking?

**Comment by johanneskoester** [comment]
Exactly, that is sufficient. Update the submodule to the latest release tag and run cargo test. Then commit the changed submodule head.

**Comment by juliangehring** [comment]
Thanks, that is good to know. Do you think that it would a good point in time to upgrade rust-htslib to htslib v1.8 then? v1.8 seems to fix a number of rare, but annoying bugs (https://github.com/samtools/htslib/releases), and the test complete successfully with the new version. I'm happy to open a PR if that helps.

**Comment by johanneskoester** [comment]
Yes, that would be awesome! Thank you!
